### ISSUE TITLE
TComponent has no constructor- All sub-classes should call parent::__construct in their constructor

### ISSUE THREAD

**Issue by ctrlaltca** [pradosoft/prado#339]
_From [google...@pcforum.hu](https://code.google.com/u/112363926660835410968/) on June 25, 2011 07:53:45_

The TComponent in the current trunk has no constructor, thus descendant classes can't call parent::__construct() to preserve a proper constructor chain, regardless of actual inheritance hierarchy. This is bad practice.

Also TPageNotFoundEventParameter tries to call parent::__construct() in its own constructor, but since neither its direct parent (TEventParameter), nor the latter's parent (TComponent) define any, it fails with a PHP error. Triggered when you try to open a non-existing page.

_Original issue: http://code.google.com/p/prado3/issues/detail?id=338_

**Comment by belisoful** [comment]
I am unifying the __construct methods.  There are many objects that wouldn't get their autoGlobalListen.  Testing this is a real pain, but it's happening.

**Comment by belisoful** [comment]
With these commits, this issue can be put to rest.

**Comment by ctrlaltca** [comment]
Fixed in #746
