### ISSUE TITLE
Update I18n support

### ISSUE THREAD

**Issue by ctrlaltca** [pradosoft/prado#439]
_From [ctrlal...@gmail.com](https://code.google.com/u/104150862989738948929/) on February 06, 2013 00:44:35_

Currently prado bundles its own copy of ICU ( http://icu-project.org/ ) data and some specific parsers in order to provide i18n and l10n support. Since the format of ICU data has changed, we're not able anymore to update our bundled ICU data, that si starting to expose its age (see per example ticket #436).

We need to either update our parsers in order to be able to bundle a newer version of the ICU data or to move to something else, like php's intl extension; since it's enabled by default on php > 5.3 and prado 3.2 needs 5.3 anyway, this could be a choice.

_Original issue: http://code.google.com/p/prado3/issues/detail?id=438_

**Comment by ctrlaltca** [comment]
Started working on this in https://github.com/pradosoft/prado/commits/intl
As usual, keeping all the existing code working is the first objective.

**Comment by samdark** [comment]
There are cons. For example, ICU data sometimes isn't up to data so one has to update it on the server. It's unlikely to be available on a shared host as well.

Some time ago I've put together this thing http://intl.rmcreative.ru/tables?locale=en_us. Could be helpful.

**Comment by ctrlaltca** [comment]
Thank you for your valuable input, @samdark. I already saw and used your website while looking how the data was been indexed in php's ResourceBundles, it was really useful.
Prado is currently bundling CLDR data from 2009, so I'm quite confident that any version available in php's Intl extension will surely be more up to date.
Of course there's still a possible problem on shared hosting, the Intl extension could not be available at all, but that's a good hint that you probably need to look around for a better hosting.
