### ISSUE TITLE
TInPlaceTextBox: PlaceHolderText property

### ISSUE THREAD

**Issue by Jumper303** [pradosoft/prado#493]
Hi,

it would be nice to have a PlaceHolderText property in TInPlaceTextBox to set default text when the field is empty.

It would be also great if the PlaceHolderText would be removed from the edit box  when you start to edit the content (The generated input field).

Something similar:

    public function getPlaceHolderText() {
        return $this->getViewState('PlaceHolderText', '');
    }

    public function setPlaceHolderText($value) {
        $this->setViewState('PlaceHolderText', $value, '');
    }

    public function setText($value) {
        if (strlen($value) == 0) { 
            $value = $this->getPlaceHolderText();
        }
        parent::setText($value);
    }

**Comment by LCSKJ** [comment]
Since HTML5 supports a placeholder attribute, it can be easily achieved using

```html
<com:TTextBox Attributes.placeholder="Enter text here..." />
```

or programmatically

```php
$textbox = new TTextBox();
$textbox->setAttribute('placeholder', 'Enter Text here ...');
```
This way no JS or value comparsion needed and supported by all modern browsers (see http://caniuse.com/#feat=input-placeholder).
