### ISSUE TITLE
RequestTimeOut does not work if hasPriority is false

### ISSUE THREAD

**Issue by david0** [pradosoft/prado#523]
Hi,
I'm not sure if this is a bug.
Callbacks with `HasPriority=false` are not affected by `RequestTimeOut`. For me this looks inconsistent. At least this side effect should be documented.
Lately I was removing some `HasPriority="true"` lines from our code and was later wondering why the request was cancelled.

Testcase:

Home.page:̀
```xml
<html>
  <head>
     <title>Request Timeout Demo</title>
   </head>
  <body>
    <com:TForm>
      <com:TActiveButton Text="Click me" OnClick="buttonClicked" ClientSide.RequestTimeOut="10000" ClientSide.HasPriority="False"  />
    </com:TForm>
  </body>
</html>
```

Home.php
```php
<?php
class Home extends TPage
{
        public function buttonClicked($sender,$param)
        {
                sleep(20);
                $sender->Text="clicked ".time();
        }
}
```

**Comment by ctrlaltca** [comment]
RequestTimeout has been fixed in 9429198310b54a3cf1eefe81a1e1964fb9b8274b. HasPriority never really worked in the jquery branch anyway.
