### ISSUE TITLE
Can't set a url mapping pattern class in php config.

### ISSUE THREAD

**Issue by plachance** [pradosoft/prado#543]
TUrlMapping line 244 :

$class=null;
if(!isset($url['class']))
	$class=$defaultClass;
$properties = isset($url['properties'])?$url['properties']:array();
$this->buildUrlMapping($class,$properties,$url);

If you set the class of a url mapping pattern in the php application configuration, it is set to null. The component creation fail because the class name is null.

**Comment by ctrlaltca** [comment]
Merged your PR, thank you!

**Comment by david0** [comment]
Has been merged, closing.
