### ISSUE TITLE
ajax3.js

### ISSUE THREAD

**Issue by majuca** [pradosoft/prado#545]
Hi,

In the function Prado.Callback (line 878) you return false. Why don't you return the request like this ?

Prado.Callback = function(UniqueID, parameter, onSuccess, options)
{
	var callback =
	{
		'EventTarget' : UniqueID || '',
		'CallbackParameter' : parameter || '',
		'onSuccess' : onSuccess || jQuery.noop()
	};

	jQuery.extend(callback, options || {});

	var request = new Prado.CallbackRequest(UniqueID, callback);
	request.dispatch();
	return request;
};

Indeed, it interested for us to have it in custom component.

Bets regards

**Comment by ctrlaltca** [comment]
I think it's a good idea, i will apply the proposed change.

**Comment by david0** [comment]
@majuca Thanks!
@ctrlaltca  I applied the change (also to Prado.JuiCallback)
