### ISSUE TITLE
Use composer-installer for 3rdparty code

### ISSUE THREAD

**Issue by david0** [pradosoft/prado#548]
To me it looks like a good thing if we would use [composer installer](http://robloach.github.io/component-installer/) to install [components/jquery](https://packagist.org/packages/components/jquery), [components/jqueryui](https://packagist.org/packages/components/jqueryui), [bootstrap](https://packagist.org/packages/components/bootstrap) and maybe the others instead of packing our own version.

That would even give users of Prado a chance to select a specific version (including a custom) if they need.

**Comment by ctrlaltca** [comment]
:+1: 
I'm already working on a tighter composer support in the "namespace" branch. Once that is complete, removing all 3rd-party components we depend upon and having them installed via composer is surely a good idea.
Some of them are not available on packagist or even not developerd anymore (eg: the old texthighlighter), but surely more recent alternatives exists.

**Comment by ctrlaltca** [comment]
This has been implemented in the current master.
