### ISSUE TITLE
TSqlCriteria, not possible to reset value of condition

### ISSUE THREAD

**Issue by jojoinside** [pradosoft/prado#549]
In TSqlCriteria, it's impossible to reset value of condition. When an empty string or null is passed to the method setCondition(), the [value _condition is not set](https://github.com/pradosoft/prado/blob/master/framework/Data/DataGateway/TSqlCriteria.php#L129-L131). Is there a reason why it's done like that ?

**Comment by majuca** [comment]
Hi,

According to the issu 549, there are an error. It must not be

if(empty($value)) {
   // reset the condition
  $this->_condition = '';
  return;
}

but:

if(empty($value)) {
   // reset the condition
  $this->_condition = null;
  return;
}

**Comment by ctrlaltca** [comment]
fixed by #555
