### ISSUE TITLE
TActivePager not working correctly on XAMP 5.6.3 (PHP, Windows)

### ISSUE THREAD

**Issue by sicutdeux** [pradosoft/prado#550]
Well, I'm not really sure where to report the issue, I've tested this on several different machines with windows x86 and amd64, different versions of XAMP also, and if you add a TActivePager with  TActiveRepeater, the behavior is estrange, sometimes doesn't render the content of the Repeater or if i add Decorators it doesn't render the buttons as the page changes, but if create a VM with ubuntu server (almost any version i could test)  it works properly. 

Any ideas?

**Comment by sicutdeux** [comment]
Well testing a little bit further, if copy and rename a TActivePager to MActivePager the callback doesn't redraw the pager, probably a javascript thing.

**Comment by sicutdeux** [comment]
Well the issue seams to be here:

``` php
public function handleCallback ($sender,$param)
	{
		// Update all the buttons pagers attached to the same control.
		// Dropdown pagers doesn't need to be re-rendered.
		$controlToPaginate=$this->getControlToPaginate();
		foreach ($this->getNamingContainer()->findControlsByType('TActivePager', false) as $control)
		{
			if ($control->getMode() !== TPagerMode::DropDownList && $control->getControlToPaginate()===$controlToPaginate)
			{
				$control->render($param->getNewWriter());
				// FIXME : With some very fast machine, the getNewWriter() consecutive calls are in the same microsecond, resulting
				// of getting the same boundaries in ajax response. Wait 1 microsecond to avoid this.
				usleep(1);
			}
		}
		// Raise callback event
		$this->onCallback($param);
	}
```
This should be changed to take the name of the class instead of the component itself, sugestions?.

**Comment by LCSKJ** [comment]
The problem might be the same as in your code snippet where it says FIXME :-) ... on fast machines the boundary of the TActiveRepeater in the javascript response is the same as the boundary of the associated TActivePager. You may try to add a usleep(1) at another point within the TActiveRepeater source.

88	private function renderPager() {
89		$pager=$this->getPage()->findControlsByType('TActivePager', false);
90		foreach($pager as $item) {
91			if($item->ControlToPaginate==$this->ID) {
92				$writer=$this->getResponse()->createHtmlWriter();
93				usleep(1); // <- ADD THIS
94				$this->getPage()->getAdapter()->registerControlToRender($item,$writer);
95			}
96		}
97	}

**Comment by javalizard** [comment]
This is a threading issue.  a better solution is to encapsulate and/or embed the render function with concurrency and synchronization.
http://php.net/manual/en/threaded.synchronized.php

**Comment by sicutdeux** [comment]
Working fine if change the TActivePager to MActivePager, but i think javalizard has a point too.

**Comment by javalizard** [comment]
As software and hardware gets more advanced, these issue may become more commonplace.  This issue points to a larger solution of threading the entire page render process to ensure render blocks are not interrupted when written.  Just an idea.

**Comment by LCSKJ** [comment]
@sicutdeux If you change TActivePager to MActivePager it woll not be re-rendered by the repeater automatically, since the above snippet will not register the pager for rendering. This is also the reason why it seems to be working, since no duplicate boundary will be created.

The problem is, that microtime() is used to create a boundary which will not really create a unique identifier if it gets called within the same microsecond - thus the usleep(1) when the boundary creation is called consecutively in a loop.
Not sure if threading really helps here if the process stays the same, since it's not really an interruption issue. If concurrent threads are getting synchronized fast enough, the problem stays the same.

A fast and easy fix might be to ensure a unique boundary by not relying on microtime, my approach would be to use uniqid() with more_entropy set to true to avoid collisions within the constructor of TCallbackResponseWriter:

```php
public function __construct()
{
    //$this->_boundary = sprintf('%x',crc32(microtime()));
    $this->_boundary = sprintf('%x',crc32(uniqid(null, true)));
}
```

**Comment by javalizard** [comment]
easiest solution yet.  thumbs up

**Comment by javalizard** [comment]
All __construct methods should calling parent::__construct to maintain proper construction chaining and construction features such as new instance class behaviors, auto listening, etc.

**Comment by LCSKJ** [comment]
Yes, you are right ... just changed the original constructor which doesn't call parent either :innocent:

**Comment by javalizard** [comment]
(all constructors may need to be updated...   I went through and updated the constructor chain on most classes a while ago...  someone saw fit to remove it though as it was redundant [at the time] just as I was updating the TComponent Class with behaviors, class behaviors, etc.)
