### ISSUE TITLE
Add option to render prado scripts at the beginning of the form

### ISSUE THREAD

**Issue by mcinp** [pradosoft/prado#551]
The decision to render the js links at the end of form that was made between Prado 3.1.10 and 3.2.0 is limiting in scenarios where one has to add custom javascript code in TTemplateControl or in a page contained in master page, where TContentPlaceholder is placed inside TForm
I came across this while updating application to Prado 3.2 - some code just stopped working.
The reason is that any javascript code inside `<script>` tag placed inside TForm that is using prototype or any other script rendered by TClientScriptManager is failing.
Take a look at simple example code - it runs perfectly on Prado 3.1.10, (the TextBox gets disabled), but on Prado>=3.2.0 there is a JS error 
"Uncaught ReferenceError: $ is not defined"

Maybe there should be an option (attribute of TForm? ) to decide whether prado js  files are linked  at the beginning or at the end of Form? Or option for TClientScript to render its contents with registerEndScript instead of in place?

There is a workaround to set another TContentPlaceholder when using master pages but there's no sych option then TTemplateControls are involved.

The code: https://www.dropbox.com/s/834088g8g4len9t/notdefined.zip?dl=1

![2015-04-09 20_06_33-itg-for-prado-3 2 4 - netbeans ide 8 0 2](https://cloud.githubusercontent.com/assets/5221388/7073512/3b1e4a70-def4-11e4-9aa7-1a3b3a16d08e.jpg)

![2015-04-09 20_09_04-itg-for-prado-3 2 4 - netbeans ide 8 0 2](https://cloud.githubusercontent.com/assets/5221388/7073524/526d1d5a-def4-11e4-9e97-5d55f84b2e81.jpg)

**Comment by mcinp** [comment]
There is yet another scenario without workaround - when using TMultiView and you want different javascript in different views.

**Comment by david0** [comment]
Did you try using [TClientScript](http://www.pradosoft.com/docs/manual/class-TClientScript.html) with `FlushScriptFiles`?

**Comment by ctrlaltca** [comment]
Closing. Feel free to reopen if further discussion is needed.
