### ISSUE TITLE
TJavascriptLogger error

### ISSUE THREAD

**Issue by cezarpirajant** [pradosoft/prado#552]
* OS: Linux Mint 17.2 64-bit
* Browser: Google Chrome 44.0.2403.125 (64-bit)
* PRADO: 3.2.4

I'm getting a error on Chrome when i'm trying to use the TJavascriptLogger:

> Error in (http://localhost/index.php?page=Dummy) on line undefined: 
[object ErrorEvent]
> Error in (http://localhost/index.php?page=Dummy) on line undefined: 
[object ErrorEvent]

I identified the source of the on the line 304 of *logger.js* file, the prototype *error* event attachment to the *window* object. I tried to use the jQuery's `on('error', handler)`, but i got the same error.

To work i had to change the event attachmento to pure javascript: 

```javascript
//Event.observe(window, 'error', function(msg, url, lineNumber) {Logger.error("Error in (" + (url || location) + ") on line "+lineNumber+"", msg)});
window.onerror = function(msg, url, lineNumber) {Logger.error("Error in (" + (url || location) + ") on line "+lineNumber+"", msg)}
```
Another suggestion to the contributors is to create a replacement to the old TJavascriptLogger, wich can use only the browser console. I can help if needed.

**Comment by ctrlaltca** [comment]
Prado 3.2.4 still uses prototype as its javascript framework. If you added jQuery to the page, it's probably overloading the definition of $, breaking prototype-base controls like TJavascriptLogger.
The solution for prado 3.2 was to use query in compatibility mode (`jQuery.noConflict()`)
The upcoming prado 3.3 dropped prototype and started using jQuery.
By the way, TJavascriptLogger was useful in the old times, when browsers didn't have good developer tools. Nowadays, chrome's internal developer tools are way more useful than TJavascriptLogger.
