### ISSUE TITLE
PRADO web page

### ISSUE THREAD

**Issue by jpuerta2011** [pradosoft/prado#556]
Hello,

Sorry, but I saw no other place for this question, one knows when will be available the http://www.pradosoft.com/ page, because when not active.

Thank you for your help

**Comment by ctrlaltca** [comment]
Sorry for the problem; we're looking into it.

**Comment by Airakath** [comment]
I ping the server before yesterday to retrieve the IP and locate the server. So I called the https://www.hetzner.de/ societer before yesterday they reported that their server not answered. He is telling me that the neccessary ferrais

**Comment by Airakath** [comment]
until you can enter the local documentation

http://localhost/"path"/prado-3.2.4.re2e58b8/demos/quickstart

**Comment by Airakath** [comment]
Prado is dead ?

**Comment by ctrlaltca** [comment]
we still didn't sort out the problems with the website.

**Comment by ctrlaltca** [comment]
Update: the server hosting PRADO's website died. A new server has been put in place, and we are currently extracting the old website and forum contents from the backup archive.
By now the server is answering at http://www.pradoframework.net/ , the other domains will be pointed as soon as possible. Thank you for you patience.

**Comment by jpuerta2011** [comment]
thanks for your work, I really need the website.

**Comment by ctrlaltca** [comment]
Update: 
Bad news: still no news from the domain owner (@qiangxue please have a look at my emails), and still no forum backup received from @rojaro. 
Good news: the main pages of the site and the manual are up at http://www.pradoframework.net/

**Comment by majuca** [comment]
step by step .-), ;-), great and thanks for your work

**Comment by ctrlaltca** [comment]
So, i gave up waiting for the old owners to help out. All references to pradosoft.com has been wiped out from the code, and everything's pointing to this github repo.
http://www.pradoframework.net/ will stay up providing demos and documentation.
I'm quite saddened for losing the forum contents, that was really valuable as a source of troubleshooting.
