### ISSUE TITLE
TWsat problem when generate AR

### ISSUE THREAD

**Issue by hermans** [pradosoft/prado#557]
Hello,

When i checked "Build Relations:" i get error message:

[Notice] Undefined offset: 0 (@line 88 in file /home/.../prado/prado3.3/framework/Wsat/TWsatARGenerator.php).

**Comment by darthdaniel85** [comment]
Hi Hermans, what kind of DB are you using?

**Comment by hermans** [comment]
i use mysql

**Comment by hermans** [comment]
My Storage Engine use MyISAM

**Comment by darthdaniel85** [comment]
You need to use InnoDB with real relationships in order to auto generate AR relations with PRADO... With MyIsam you cant have physical relations. Nonetheless I need to add a validatios for those cases.

**Comment by hermans** [comment]
thanks, that need to validation if not in InnoDB
