### ISSUE TITLE
Suggesting new feature "TClientStyleSheet"

### ISSUE THREAD

**Issue by camilohaze** [pradosoft/prado#562]
Good afternoon,

I would like to make a suggestion for a feature which would have a similar "TClientScript" behavior but in this case it would not render a JS file if a CSS file as an idea for the name would be "TClientStyleSheet" and that likewise allow register a package of CSS files.

```html
<com:TClientStyleSheet PradoStyleSheet="bootstrap" />
<com:TClientStyleSheet StyleSheetUrl=<%~ test.css %> />
```

**Comment by ctrlaltca** [comment]
Maybe what you want is this: http://pradosoft.github.io/docs/manual/class-TStyleSheet.html
Example usage:
```
<com:TStyleSheet StyleSheetUrl=<%~ comments.css %> />

<com:TStyleSheet>
.greenbold_button {
	background-color: #0f0;
	font-weight: bold;
}
</com:TStyleSheet>
```

**Comment by camilohaze** [comment]
But it is possible that these styles are added from a package as "TClientScript" work?

**Comment by ctrlaltca** [comment]
No, this doesn't exists yet.
Example for TDatePicker, the whole "datepicker" js package is published:
```
	protected function registerCalendarClientScriptPre()
	{
		if($this->getShowCalendar())
		{
			$cs = $this->getPage()->getClientScript();
			$cs->registerPradoScript("datepicker");
		}
	}
```

While for stylesheet, the single file is published:
```
	protected function publishCalendarStyle()
	{
		$url = $this->getAssetUrl($this->getCalendarStyle().'.css');
		$cs = $this->getPage()->getClientScript();
		if(!$cs->isStyleSheetFileRegistered($url))
			$cs->registerStyleSheetFile($url, $url);
		return $url;
	}
```

I suppose that the rationale behind this is that javascript can depend on other js such as libraries, while css files typically no dependencies exists (i can only think of css @include).

**Comment by camilohaze** [comment]
I understand your point of view, but to use the Bootstrap CSS is necessary to include the JS and its dependencies and my suggestion is declining requests for a product that only needs the CSS and use what you already have and not have meadow add an external URL or add the file to my project.

=====

Yo entiendo tu punto de vista, pero para poder usar el CSS de Bootstrap es necesario incluir el JS y sus dependencias y mi sugerencia va para la disminución de peticiones en una pagina que solo necesita el CSS y usar lo que ya tiene prado y no tener que añadir una URL externa o añadir el archivo a mi proyecto.

**Comment by ctrlaltca** [comment]
So, we could add an helper method to TClientScriptManager.php that permits to write:
```
<com:TStyleSheet PradoStyle="bootstrap3" />
```

and that will result as:
```
<com:TStyleSheet StyleSheetUrl=<%= $this->Page->ClientScript->PradoScriptAssetUrl.'/bootstrap3/css/bootstrap.css' %> />
<com:TStyleSheet StyleSheetUrl=<%= $this->Page->ClientScript->PradoScriptAssetUrl.'/bootstrap3/css/bootstrap/theme.css' %> />
```

**Comment by camilohaze** [comment]
I think a very good idea. :+1:

**Comment by ctrlaltca** [comment]
I'd keep this open as a reminder to have the feature implemented
