### ISSUE TITLE
Prado forums???

### ISSUE THREAD

**Issue by jmjimenez** [pradosoft/prado#567]
I've been using PRADO for a long time. But only partial-time. Right now, I'm involved in a new project and I would like to develop it from scratch. I'm really excited for new PRADO's improvements to use 100% jQuery.
But I really miss the old PRADO forum and all the information stored there. I know everyone is pretty busy. But, is there any chance to have it online again?

**Comment by ctrlaltca** [comment]
@rojaro was the guy ho used to host the server. When the server crashed he said he won't be able to host the site anymore, but he promised to give us a backup of the full website. Since them he doesn't answer our emails anymore, and he even deleted his github account. I don't have big expectations on getting that backup anymore, but i remember him as a cool guy so i just hope he's fine.

About the website, also blame @qiangxue for just don't giving a fuck about Prado anymore. He's the currently domain owner, we asked him more than once if the domains could be pointed to the new server but didn't even bother to reply.

**Comment by jmjimenez** [comment]
I'm sorry to read this. I remember @rojaro from the forums, he was always very helpful. As you said, I hope he is fine (there must be some reason for his behavior)
As for @qiangxue I think his work is impressive. But if he has decided to give up PRADO, perhaps he should have some responsibilites to the people who trusted this project (I really like PRADO, its architecture and all the components it includes)

**Comment by javalizard** [comment]
@rojaro spoke to me briefly many years ago.  He was discussing PRADO 4.

**Comment by yoisar** [comment]
Hello! My name is Yassel and I've been using PRADO for a  long, long time ago. 
I was in the PRADO  forum as yois. 
I've created a datagrid with grpuing columns, written in pure PHP by me. I've  proposed to include Grouping Columns to the PRADO creator, the dunky icon, I can't remember the nick name, I guess it was Quiang, or whatever.  I did some Spanish translation too. 

I have several, data interaction, components created by me and based on PRADO through this years, 
Some of those complements are the following ones :

ADataManager I use as a parent static  Class of all my tables mangers. 

BaseEditTpl: extends TTemplateControl and  Parent class for several Data Web Forms I use.

GridData: Extends from TTemplateControl, used for several  Pages the have DataGrids.

And so on...
Now..
FIRST: I think the FORUM is extremely  necessary for PRADO eternity!!!

SECOND: I offer a server with backups to reopen the forum with access to all of PRADO MANAGERS.
YOU MUST TELL ME THE SERVER SPECIFICATIONS

I'm actually  developing 4 Web Systems using PRADO Framework and my own Framework based on PRADO.
I'm Cuban, but I'm living in Argentine.
I hope this help.
Greetings!

**Comment by ctrlaltca** [comment]
Hi @yoisar , and thank you for your interest.
About the components, if you want to share them we are open for PRs.
If you want to open a forum related to PRADO, we'll be glad to link it somewhere among these pages.
Another user already came up with a similar idea, you can find the relevant informations here: https://github.com/pradosoft/prado/wiki/Unofficial-Prado-Framework-Forum

**Comment by yoisar** [comment]
Thank you for the hard work you've done to include jQuery and maintain the best PHP Framework , at least for me .
If there is a forum created , I will not reinvent the wheel .
About Components , how I can share?
