### ISSUE TITLE
TJavascript Logger not show the message

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#569]
Hello,

TJavascriptLogger is very useful for me because we know what happening when error occured.

 I have used Prado 3.3.0, why the erro message is missing in TJavascriptLogger

Thanks
![tjavascriplogger](https://cloud.githubusercontent.com/assets/7402103/13236727/d41d4e9c-d9f8-11e5-8ff9-19f5484fcfac.png)

**Comment by javalizard** [comment]
Having played around with that code once...  This may be an issue of buffering the page output.  TJavascriptLlogger depends upon the header(...) php function.  However, if the code is outputting to the network stream directly, the TJavascriptLogger is not able to write any header(...)s as the page body stops the functioning of header().

Are you/Is the framework buffering the page output until after the TJavascriptLogger runs all the header()s?

**Comment by mrizkir** [comment]
No. I'm just putting TJavascriptLogger inside the page. I have several project with TJavascriptLogger with Prado 3.2,3,3.2.1 version it's working very well.

the issue came started from Prado 3.2.4 until 3.3.0.

thanks.

**Comment by javalizard** [comment]
My apologies.  I was confusing TFirebugLogRoute with TJavascriptLogger and the call-back.

Maybe this is an issue with the jquery conversion of the active controls with callback?  where the error isn't getting passed through properly?

**Comment by ctrlaltca** [comment]
Can you test current master? i've made some changes yesterday and it seems to work now.

**Comment by mrizkir** [comment]
I have tested. this is a result :
![tjavascriptlogger1](https://cloud.githubusercontent.com/assets/7402103/13340509/63bbab4a-dc63-11e5-9a73-4e4cc2d13957.png)

Why the error message missing in TJavascriptLogger ?

**Comment by ctrlaltca** [comment]
From the [PHP manual](http://php.net/manual/en/function.set-error-handler.php):

> The following error types cannot be handled with a user defined function: E_ERROR, E_PARSE, E_CORE_ERROR, E_CORE_WARNING, E_COMPILE_ERROR, E_COMPILE_WARNING, and most of E_STRICT raised in the file where set_error_handler() is called.

In your last screenshot you have a fatal error that cannot be catched by PRADO using an error handler.
In your first comment, instead, you had a "callback server error", that it's working now:
![schermata 2016-02-26 alle 08 41 02](https://cloud.githubusercontent.com/assets/1631111/13346178/c004d4d4-dc64-11e5-8a20-73082e2e85c9.png)

**Comment by ctrlaltca** [comment]
Btw, we could add a ```register_shutdown_function``` to try to catch fatal errors. I'll have a look at this.

**Comment by ctrlaltca** [comment]
So, i've implemented a register_shutdown_function that should be able to catch fatal errors.
Still, it won't always work on callbacks if the page parsing fails before the callback error handler is set.

**Comment by mrizkir** [comment]
Ok. i thing it's enough for me. I'm just want to know what the error message when error occured.

thanks a lot.

**Comment by ctrlaltca** [comment]
Thank you for pointing out something that could be improved
