### ISSUE TITLE
Ho to use TJuiAutoComplete

### ISSUE THREAD

**Issue by yoisar** [pradosoft/prado#575]
Is there sombody who use already TJuiAutoComplete?
I'm doing this... but does not work. :-(  I get the followig error inside FireBug
`ui.item.value = previousTerms + ui.item.value; `

The code is the following one: ` <com:TJuiAutoComplete ID="clase" OnSuggest="SugiereClase"
				OnSuggestionSelected="ClaseElegida"
				Attributes.placeholder="Escriba clase" 
				Suggestions.DataKeyField="claseCatId" TextCssClass="sugerencias">
                    <prop:Suggestions.ItemTemplate>
                    <div id="sugerencias"><%# $this->Data['nombre'] %></div>
                    </prop:Suggestions.ItemTemplate>
                  </com:TJuiAutoComplete>`

**Comment by ctrlaltca** [comment]
Did you try testing the demo included in the quickstart? [demo](http://www.pradoframework.net/demos/quickstart/?page=JuiControls.Samples.TJuiAutoComplete.Home) [source code](http://www.pradoframework.net/demos/quickstart/?page=ViewSource&path=/JuiControls/Samples/TJuiAutoComplete/Home.page)

**Comment by yoisar** [comment]
yes, I did, besides I was using TAutocomplete, and replace it as QuickStart says.

**Comment by ctrlaltca** [comment]
> ui.item.value = previousTerms + ui.item.value;

This is not the error itself, it's the row of code where something (a javascript exception, i suppose) occurs. It's inside the method that gets executed when a suggested entry gets selected (OnSuggestionSelected).

A fix related to that part of the cod has been introduced after 3.3.0 has been released: https://github.com/pradosoft/prado/commit/aa421438bc13914f6ef63ca9d79499e64be9a176

Can you give Prado's current master a run and test if it your problem has already been solved?
If this is the case, i can plan to release a 3.3.1 bugfix version soon.

**Comment by ctrlaltca** [comment]
@yoisar did you manage to get your problem solved?

**Comment by ctrlaltca** [comment]
Closing. Please reopen if you need further assistance.
