### ISSUE TITLE
How to change width TJuiComplete

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#576]
Hello,

how to  change width value of TJuidComplete, I have seting width attributes of TJuiComplete, but not working.  

`<com:TJuiComplete Width="500px">`

thanks.

**Comment by LCSKJ** [comment]
I guess you mean TJuiAutoComplete - just tested setting width using master branch, works like expected. Does it show the inline style attribute in source code?

**Comment by ctrlaltca** [comment]
It's working for me, too. Taking the quickstart example and adding a width declaration to it
```html
<com:TJuiAutoComplete
    ID="AutoComplete"
    OnSuggest="suggestNames"
    OnSuggestionSelected="suggestionSelected1"
    ResultPanel.CssClass="acomplete"
    Width="500px"
    Suggestions.DataKeyField="id" >

    <prop:Suggestions.ItemTemplate>
    <li><%# $this->Data['name'] %></li>
    </prop:Suggestions.ItemTemplate>
</com:TJuiAutoComplete>
```

results in:

```html
<input name="ctl0$body$AutoComplete" type="text" id="ctl0_body_AutoComplete" style="width:500px;" class="ui-autocomplete-input" autocomplete="off">
```

**Comment by mrizkir** [comment]
Ok thanks. It's worked.
