### ISSUE TITLE
Updating selected values of active list controls during callback broken

### ISSUE THREAD

**Issue by LCSKJ** [pradosoft/prado#577]
Changes to TActiveListControlAdapter from commit cc53959ac5ba3e786f3d6ad3403919b82c52fa42 breaks updating selected values of active list controls during callback, since the corresponding methods in TActiveListControlAdapter are called at the end of the list control setter. The added condition will always evaluate true since the control's values are already changed and the adapter does not change clientside values.

@ctrlaltca i did not look into it more deeply, not sure if it can be easily fixed. if not, we may revert the changes for now admitting the callback overhead and have a deeper look into it later.

**Comment by ctrlaltca** [comment]
I'll give it a look later this day; if you need, fell free to revert it in the meanwhile.

**Comment by ctrlaltca** [comment]
Sounds like reverting is the safest option by now.
