### ISSUE TITLE
THead generate tag "<title></title>" empty

### ISSUE THREAD

**Issue by camilohaze** [pradosoft/prado#580]
When implemented the THead control, this always generates an empty tag "<title>".

**Comment by ctrlaltca** [comment]
Html4 states ```Each document must have exactly one TITLE within the HEAD.``` so, even if the title is empty, the tag should be rendered.
Html5 is more loosely defined, so the title tag can be omitted.
I suppose not rendering the title tag when empty will make no problem with any browser, but it could make pages fail at some validator.
