### ISSUE TITLE
TActiveFileUpload loses track of LocalName for a moment

### ISSUE THREAD

**Issue by emkael** [pradosoft/prado#581]
Hi,

During an attempt to implement a bit more secure version of `T*FileUpload` controls (namely: ones that optionally derive `FileType` and `FileSize` from the MIME and size detected server-side), I ran into an issue with `TActiveFileUpload`.

On the initial postback, in the `onFileUpload` event handler, uploaded file is moved from PHP's `upload_tmp_dir` to `TActiveFileUpload`'s `TempPath`. This is done via `TFileUpload`'s `saveAs` method.

The issue here is that within a few code lines down this method, there are attempts to call `getFileSize` and `getFileType`. And during these calls, there's no track of the actual local path where the uploaded file is currently being stored, since the object's `_localName` property still points to the file in `upload_tmp_dir`, from which the file was just `move_uploaded_file`'d away.

I see several possible solutions to that issue, none on which seem too intrusive:
 * compile `$params` for the client side code snippet before calling `parent::saveAs` (that way `getFileSize` and `getFileType` methods still have access to the file in `upload_tmp_dir`) - the success of `parent::saveAs` is not checked anyway (but maybe it should be?)
 * update `_localName` property after calling `parent::saveAs` in `TActiveFileUpload` (note that at the moment `_localName` is declared private in parent class, so this requires a change to a protected property)
 * update `_localName` property immediately after a successful `move_uploaded_file` call in `TFileUpload::saveAs` if it's called with `$deleteTempFile` set

The second one looks to me like a good compromise between fixing that particular issue and not altering universal behavior too much, but the last one allows developers to keep track of the server-side path to the file even after they've explicilty called `saveAs` on any instance of `TFileUpload`, so maybe it's a desired side-effect.

Have a nice day,
Michal K.

**Comment by ctrlaltca** [comment]
Can you please check if #584 correctly implements the second method you proposed and fixes the issue for you? Thank you

**Comment by emkael** [comment]
Yes, that's exactly what I've had patched locally.

Thanks :)
