### ISSUE TITLE
Prado autoloader breaks class_exists conditionals

### ISSUE THREAD

**Issue by thebeline** [pradosoft/prado#582]
The Prado auto-loader breaks conditionals using `class_exists` to determine application functionality.  When using functionality that behaves differently, contingent on the existence of a class (expected behavior), the Prado auto-loader will fatal the application (unexpected behavior).

This has also been mentioned in a [previous issue](https://github.com/pradosoft/prado/issues/446) that it will fatal the application in the event that the Prado auto-loader is not the last auto-loader registered.

This seems like disadvantageous behavior.  What is the end-goal of having Prado `exit` instead of having PHP manage the resulting error (if, indeed, failing to load the class would cause an error) instead?  If the goal is to show debugging information in the event that a class is attempted to be loaded `$obj = new \NoClass;`, it may be more advantageous to register a shutdown function that manages this (detects the fatal and issues a stack trace, this may be done already).  Perhaps have Prado issue a `E_USER_WARNING` on a failed class load, instead of exiting the application, and issue the stack trace on an internal fatal instead of calling `exit` by default.

Not sure, some insight to this behavior would be *much* appreciated.

**Comment by ctrlaltca** [comment]
Than you for your detailed report, this issue should be resolved by #583, that will hopefully ship in Prado 3.3.1 in a few days.
