### ISSUE TITLE
Calling unserialize() on TMappedStatement throws TApplicationException

### ISSUE THREAD

**Issue by emkael** [pradosoft/prado#585]
Hi,

I can see that commit 562e322fe595b4d3307ff28a96c8c5fbcc284010 removed the `__wakeup` magic method from `TComponent`.

Unfortunately, there's one direct subclass of `TComponent` which still calls `parent::__wakeup` in its `__wakeup` method: `TMappedStatement`.
This would be fine, but the parent call causes the subsequent call of `__call` method in `TComponent` (since `__wakeup` is not explicitly defined in that class), which then throws `TApplicationException` (component_method_undefined).

That exception is thrown every time there's an attempt at unserialization of a cached `SqlMapManager`, e.g. `Prado::getApplication()->getModule('sqlmap')->getClient()` when there's a cache module available.

From what I can tell, the quick fix of dropping `parent::__wakeup` invocation from `TMappedStatement::__wakeup` fixes this issue, as well as reintroducing `__wakeup` method to `TComponent`.
But maybe `TComponent::__call` shouldn't throw exceptions (or do anything special) on attempts to call magic methods?

Also, would it be more useful if I opened pull requests, even for such seemingly minor code changes?

Cheers,
Michal K.

**Comment by ctrlaltca** [comment]
> Also, would it be more useful if I opened pull requests, even for such seemingly minor code changes?

A PR is worth a thousand words :+1:

**Comment by ctrlaltca** [comment]
Can you have a look at https://github.com/pradosoft/prado/pull/586/files and see if that works for you? Thank you

**Comment by emkael** [comment]
The change in `TMappedStatement` on its own fixes that particular issue.

For the change in `TComponent`, I was thinking more about something in lines of:
```
if (!method_exists($this, $method)) {
    throw new TApplicationException('component_method_undefined',get_class($this),$method);
}
```
around the exception throwing code.

I know it's a strange condition to have in a `__call` method, but should also cover any strange cases other than magic methods (that I honestly cannot imagine at the moment :) ).

**Comment by ctrlaltca** [comment]
> I know it's a strange condition to have in a __call method

Yes, indeed. Won't that always evaluate to ```true``` anyway making the ```if()``` useless?

Also, looking again at #586, i'm not sure if it's a good idea to suppress any error thrown when a __magicMethod is called but not implemented.

I'm quite convinced to fix TMappedStatement and leave TComponent as is, unless there's a good reason to avoid throwing a TApplicationException in some cases. Is there any case?

**Comment by emkael** [comment]
> Yes, indeed. Won't that always evaluate to true anyway making the if() useless?

That's the quirk of it (actually, that's a borderline bug behavior on PHP's behalf, to be honest, but maybe there's a reason behind it).

From what I can tell, `method_exists($this, '__magicMethod')` always returns `TRUE` even if `__magicMethod` is not explicitly defined in a class - I'm guessing it just falls back to native object code. And that's the case this `if()` filters out.

PHP's inconsistency here is that an explicit call to `$object->__magicMethod()` does not invoke `__call` when `__magicMethod` is not defined in a class, but a `parent::__magicMethod()` in a subclass - does. It's as strange as one would imagine.

**Comment by ctrlaltca** [comment]
ok you convinced me :confused:

**Comment by ctrlaltca** [comment]
PR updated and merged, thank you for the detailed explanation on the problem.

**Comment by emkael** [comment]
Just to follow-up: I've run some additional tests and the thing about `method_exists` is not as strange as I thought after all.

It's just a matter of `method_exists($this, '__magicMethod')` returning TRUE if the *subclass* implements it, not a fall back to native code, sorry for confusion on that one.

There's still that quirk of invoking `__call` when `parent::__magicMethod` is called, so that still fixes any `parent::__magicMethods` calls in `TComponent` subclasses, though.
