### ISSUE TITLE
page vs html

### ISSUE THREAD

**Issue by yoisar** [pradosoft/prado#590]
I alwas have to do this
Inside pradolite.php
// const PAGE_FILE_EXT='.page';
const PAGE_FILE_EXT = '.html';
And Inside Web/Services/TPageServices.php
// const PAGE_FILE_EXT='.page';
const PAGE_FILE_EXT = '.html';

Is there any way to do this through configuration?
I have several sites developed in prado and always I have an upgrade version I have to do that!

**Comment by yoisar** [comment]
Because I use DW and other development tools that do not recognize or work with files .page becomes tedious

**Comment by ctrlaltca** [comment]
Break everyone's existing application using Prado is not such a good idea, instead i'd suggest you  to add `.page` to your dreaweaver's recognized extensions in the config file: https://helpx.adobe.com/dreamweaver/kb/change-add-recognized-file-extensions.html

**Comment by yoisar** [comment]
Ok, I'll try it. I have too many Templates files to rename. But I'll do my best!
