### ISSUE TITLE
Magic method (__isset, __get) control (TStdButton for example) and empty() cannot be correctly evaluated

### ISSUE THREAD

**Issue by jojoinside** [pradosoft/prado#594]
In my template, I have a TStdButton with ID **test** (same with other control...), in my method called on the OnClick, I made theses following tests (PHP7 and Prado 3.3.1) :

`$value = $this->test;`
Ok, For **test**, use magic method __get of TControl

`$value = empty($this->test);`
KO, For **test**, use magic method __isset of TComponent, return false because any method getTest() exists (it's only an item in an array as I've seen in the magic method __get of TControl

`$value = $this->test->Text;`
Ok, For **test** and **Text**, use magic method __get of TControl

`$value = empty($this->test->Text);`
KO, For **test**, use magic method __isset of TComponent, return false because any method getTest() exists (it's only an item in an array as I've seen in the magic method __get of TControl

`$value = $this->test->getText();`
Ok, For **test**, use magic method __get of TControl and for getText() method getText

`$value = empty($this->test->getText());`
Ok, For **test**, use magic method __get of TControl, because use of getText I would say...

In 2 tests, empty cannot evaluate correctly **test** because any get method exists for **test**

**Comment by jojoinside** [comment]
Here is proposition of modification in TControl.php (same way as __get)

```
public function __isset($name) {
	if(isset($this->_rf[self::RF_NAMED_OBJECTS][$name])) {
		return true;
	} else {
		return parent::__isset($name);
	}
}
```

**Comment by ctrlaltca** [comment]
I think you have a good point here in making the result of isset(X) congruent with the one of getX().
I'll make some tests to ensure this doesn't break anything, and will implement this once the tests are complete.
By the way, what is a ```TStdButton```? I suppose you subclassed a ```TButton```.

**Comment by jojoinside** [comment]
Great! Sorry, you're right it's a subclass, but I would say it doesn't change anything

**Comment by ctrlaltca** [comment]
Yep, it was just out of curiosity

**Comment by ctrlaltca** [comment]
Proposed patch has been merged, thank you
