### ISSUE TITLE
Remove mcrypt usage

### ISSUE THREAD

**Issue by ctrlaltca** [pradosoft/prado#595]
MCrypt is abandonware, it raises a deprecate notice on php 7.1 and will be removed in a following release: https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by LCSKJ** [comment]
I rewrote the TSecurityManager to use OpenSSL instead of mcrypt in pull request #622.

@ctrlaltca You should review the comment for the pull request for details and merge if acceptable.
