### ISSUE TITLE
Prado template engine

### ISSUE THREAD

**Issue by konstantinrachev** [pradosoft/prado#598]
Hi guys,

Is it possible to change Prado's default template engine as I feel it a bit buggy and I would say not stable?

Thanks in advance.

**Comment by ctrlaltca** [comment]
Sorry, but i really don't know what a good answer to your question could be.

> Is it possible to change Prado's default template engine

By now Prado uses its own template engine. What do you want to use instead?

> as I feel it a bit buggy and I would say not stable

If you experienced problems, please report them so that we can see if there are bugs to fix, documentations to improve, etc..

**Comment by ctrlaltca** [comment]
Closing as: whatever happened we'll never know.
