### ISSUE TITLE
TWizard label message not multi language

### ISSUE THREAD

**Issue by chbomutex** [pradosoft/prado#602]
TWizard label message are not configurable to a different language  (default text is in  english)

I would like to have 'Next' and 'Previous' in french  : 'Précédent'  and 'Suivant'

**Comment by ctrlaltca** [comment]
The quickest solution is to set the ButtonStyle properties:
```
<com:TWizard ID="Wizard1"
  ...
  StartNextButtonStyle.ButtonText="Next"
  StepNextButtonStyle.ButtonText="Next"
  StepPreviousButtonStyle.ButtonText="Previous"
  FinishCompleteButtonStyle.ButtonText="Complete"
  FinishPreviousButtonStyle.ButtonText="Previous"
  CancelButtonStyle.ButtonText="Cancel"
>
```

A more complete solution is to create a custom template. Have a look at Example 4 at http://127.0.0.1/prado-master/demos/quickstart/index.php?page=Controls.Wizard
