### ISSUE TITLE
Prado in CentOS7

### ISSUE THREAD

**Issue by Felipeao** [pradosoft/prado#603]
Hi, 

I'm working in Prado 3.2.3 actually, I develop in Windows 7, but now I need to release the project in a server with Linux CentOS 7, I wanna know, has anyone tested Prado in CentOS 7? The documentation in the page of Prado Framework says that it works in various distros.
I have checked the paths, every file had their respective permissions... But when I try to test my application never dispatch the events (onClick, onInit, onLoad), and show me the next error: "_Component event 'TActiveButton.onclick' is attached with an invalid event handler 'TemplateControl.btnLogin_OnClick'_"

I need some help with this.

**Comment by ctrlaltca** [comment]
Sure it works in Centos 7. I'm running some Prado webapps on a Centos 7 VPS hosted by [Gandi](http://www.gandi.net/), and they just work fine. The only thing, the PHP version provided by Centos is quite old, so i just suggest you to upgrade 5.6 using Webatic's packages: https://webtatic.com/packages/php56/

> "Component event 'TActiveButton.onclick' is attached with an invalid event handler 'TemplateControl.btnLogin_OnClick'"

This means that that you have some template code like this:
```
<com:TActiveButton
  ID="btnLogin"
  OnClick="btnLogin_OnClick"
>
```

but Prado is not able to find a function named "btnLogin_OnClick" in the php file associated to the template. Either the method doesn't exists or Prado is looking for it on the wrong scope. A common solution for the second case is explicitly declaring the scope like this:
`OnClick="Page.btnLogin_OnClick"`
or
`OnClick="SourceTemplateControl.btnLogin_OnClick"`

**Comment by Felipeao** [comment]
Thanks for the answer. 

I'm developing in PHP 5.4.4, and I can't change it.

My button is in this path "app/protected/View/app/Login/Login.page", and the code is:  <com:TActiveButton CssClass="btn btn-primary pull-right" ID="btnLogin"
                                    TabIndex="4" Text="Entrar" ValidationGroup="login"
                                    OnClick="btnLogin_OnClick"
                                    />
The controller is in: "app/protected/Controller/app/Login/Login.php", and it has a function like this: 
 ```
public function btnLogin_OnClick($sender, $param){
        try{ ...
}catch(Exception $e){
            $this->CallbackClient->callClientFunction('mostrarMensaje', array($e->getMessage(), 'error'));
        }
    }
```
I have typed the onClick of the button: Page.btnLogin_OnClick, page.btnLogin_OnClick, TemplateControl.btnLogin_OnClick, SourceTemplateControl.btnLogin_OnClick, SourceLogin.btnLogin_OnClick, Login.btnLogin_OnClick, login.btnLogin_OnClick, Sourcelogin.btnLogin_OnClick...

What else?

**Comment by ctrlaltca** [comment]
> My button is in this path "app/protected/View/app/Login/Login.page"
> The controller is in: "app/protected/Controller/app/Login/Login.php"

In Prado, a php class file (.php) and its template file (.page/.tpl) are supposed to live in the same directory. From http://pradoframework.net/demos/quickstart/?page=Fundamentals.Pages:
`
Each page can have a template file. The file name suffix must be .page. The file name (without suffix) is the page name. PRADO will try to locate a page class file under the directory containing the page template file. Such a page class file must have the same file name (suffixed with .php) as the template file. If the class file is not found, the page will take class TPage.
`

**Comment by Felipeao** [comment]
Yeah, sure, it's supposed to be in the same directory, but I'm using MVC, so I needed it in diferents paths, In windows the webapp works fine. What can I type in the onClick event for linux? 

I tried Controller.btnLogin_OnClick, but it says "Component property 'TActiveButton.Controller' is not defined."

**Comment by ctrlaltca** [comment]
> Yeah, sure, it's supposed to be in the same directory, but I'm using MVC, so I needed it in diferents paths,

This statement doesn't really make any sense to me. Prado won't be able to load the file if it's not in the same directory, and MVC is not a magic switch that's enabled by moving files in another directory.

> In windows the webapp works fine.

I'm sorry, but that's not possible, unless you overloaded the template loading mechanism in TemplateManager or something fishy is going on in the php windows installation.
