### ISSUE TITLE
URL Mapping (Friendly URLs)

### ISSUE THREAD

**Issue by Airakath** [pradosoft/prado#605]
Hello, 
I'm sorry, i don't really know where to post this message, 
I need some more informations about URL Mapping, I didn't find any answers.
I would like to know how to put in parameters mode a string rather an integer. 
Thanks to help me as soon as possible, have a nice day.

**Comment by ctrlaltca** [comment]
In application.xml:
```xml
<module id="request" class="THttpRequest" UrlFormat="HiddenPath" UrlManager="friendly-url" />
<module id="friendly-url" class="System.Web.TUrlMapping" EnableCustomUrl="true">
  <url ServiceParameter="Pages.MyPage" pattern="pages/{id}/" parameters.id="[0-9a-fA-F]"/>
```

In this example the page "MyPage.php" will be called when the user requests the url http://site.tld/pages/string, and the "string" parameter will be available as the "id" parameter in the request:

Mypage.php
```php
		$id=TPropertyValue::ensureString($this->Request['id']);
```

More informations here: http://pradoframework.net/demos/quickstart/?page=Configurations.UrlMapping
