### ISSUE TITLE
Problem getting value inside JuiDialog

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#606]
Hello, i want to get value from textbox inside JuiDialog. The problem is why the value is Empty. here is my code :

filemanager.page :
```
...................
....................
<com:TJuidDialog ID="dialogCreateNewDir" 
                  Options.Title="Buat Folder Baru"
                  Options.AutoOpen="False">

       Enter Folder Name : <com:TActiveTextBox ID="txtNewDir" />
       <com:TJuiDialogButton OnClick="createDir">
               <prop:Text>                                        
                     Create                                        
                 </prop:Text>                            
        </com:TJuiDialogButton>
</com:TJuidDialog>
```
filemanager.php :
```
................
................
public function createDir ($sender,$param) {
          echo $this->txtNewDir->Text;
}
```

Thanks...

**Comment by ctrlaltca** [comment]
The only problems i see in your code are:
 1. `TJuidDialog` is mispelled, the correct name is `TJuiDialog`
 2. if you `echo` the value, you won-t see anywhere in the page. You'd better write it to a `TActiveLabel`

Anyway, i've added a working example on the quickstart tutorial, you can see it working here: http://pradoframework.net/demos/quickstart/?page=JuiControls.Widgets#TJuiDialog
