### ISSUE TITLE
Unwanted screen using 3.3.2 framework on IIS

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#610]
Hello.

I'm testing a new environment (windows server 2008, IIS 7.5, PHP 5.6.24). I've run the login form used in the #608 issue i previously submit and this screen (image) appear forcing me to click before going to the next page.
![image](https://cloud.githubusercontent.com/assets/20577647/18167681/c8e5f712-7049-11e6-8494-90addc849110.png)

This occur when I use the 332 framework and not on the 324 framework.
[issue_iis.zip](https://github.com/pradosoft/prado/files/449648/issue_iis.zip)

**Comment by ctrlaltca** [comment]
The login button is probably redirecting to a null page.
```
$this->Response->redirect($this->Request->constructUrl($this->Service->ID, 'login_old'));
```
This should look like:
```
$this->Response->redirect($this->Service->ConstructUrl('Pages.NameOfThePage', array('param' => 'value'));
```

**Comment by frkinta** [comment]
Thank you for your answer.
The login button is redirecting to an existing page. After changing the constructor, the problem still remain.

**Comment by frkinta** [comment]
Hello,

When I change the "helloworld" `home.php` to

```PHP
class home extends TPage {
    public function buttonClicked($sender, $param) {
        $this->Response->redirect('home');
    }
}
```
on IIS 7.5/Windows server I have the issue described before

**Comment by ctrlaltca** [comment]
So, here's the backstory:
When you redirect(), prado internally sends a Location header using php's [header](http://php.net/manual/en/function.header.php) function.
PHP states that:

> The second special case is the "Location:" header. Not only does it send this header back to the browser, but it also returns a REDIRECT (302) status code to the browser unless the 201 or a 3xx status code has already been set.

This is currently not working as expected on IIS, so the fix was to force sending the correct http status code.

**Comment by ctrlaltca** [comment]
As an unrelated note, i see in you code:
```php
$this->Response->redirect('home');
```

while you may probably want to do instead:
```php
$this->Response->redirect($this->Service->constructUrl('home'));
```

**Comment by frkinta** [comment]
It work. 
Thank for your advise
