### ISSUE TITLE
Control for Input type Number

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#613]
Hello,

what kind prado control for input type number like this :
`
<input type="number" value="<%#$this->DataItem['qty']%>" name="qty" maxlength="3" max="999" min="1" />
`

Thanks

**Comment by ctrlaltca** [comment]
It's currently missing. We need to add a proper `TTextBoxMode` mode in order to support new types, or create new controls.

**Comment by ctrlaltca** [comment]
Support for the new input types added in html5 has been added. You need to use prado's "master" or wait for a new version to come out in order to be able to use them.
Thank you for the hint.
