### ISSUE TITLE
TAdoDBProvider

### ISSUE THREAD

**Issue by Laayem** [pradosoft/prado#614]
Hello, 

This is an issue with your framework, but maybe you can help.
My boss want me to install an app based on prado framework, but I'm stuck on this error :
![selection_075](https://cloud.githubusercontent.com/assets/20817470/20621606/6fd82c1e-b2ff-11e6-80ed-2c07d7690d9f.png)

I've searched all the web but I can't find any reference of this TAdoDBProvider.php... Is this a file used on an older version of Prado? Or is it a AdoDB file?

Thank you for any help or hint you can gave me.

Laayem

**Comment by ctrlaltca** [comment]
That app has been written for an ancient version of Prado.
Just to give you an idea, the file you're missing has been created on Feb 22, 2006 and removed on May 18, 2006. It only briefly existed in some beta and rc before the release of version 3.0.0.

**Comment by Laayem** [comment]
Thank you for your quick answer.
Now I have to inform my boss that he just bought an app based on a 10 year old beta framework.
