### ISSUE TITLE
TCheckbox and TRadioButton html render for bootstrap

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#618]
Ok. I have another problem.

Actually the TCheckBox html result is 

```
<span id="ctl2_parent">
  <input id="ctl2" name="ctl2" type="checkbox">
  <label for="ctl2">Checkbox text</label>
</span>
```

Is it possible for better bootstrap and plugins uses to have instead

```
<label>
    <input type="checkbox" value="" name="">
    Checkbox text
</label>
```

?

**Comment by LCSKJ** [comment]
Have a look at issue #617 - the solution for your problem is similar, you may use `setPreTagText()` and `setPostTagText()` of `TWebControlDecorator` accordingly to wrap the checkbox with your markup (putting it together in a skin file makes it easier to reuse).
