### ISSUE TITLE
How to associate TEmailLogRoute and PHPmailer if PHP mail function is disabled?

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#620]
Hello,
I would like to receive some log message through TEmailLogRoute. PHP mail function is not enabled on my server (shared hosting). 

Is it possible to "Route" logs using PHPmailer?

**Comment by LCSKJ** [comment]
You may extend TEmailLogRoute overwriting processLogs() method, there you can instantiate PHPmailer and use it's functionality to send the mail. Or even write your own log route directly extending the abstract class TLogRoute.

**Comment by ctrlaltca** [comment]
Example implementation: 

protected/application.xml:
```xml
    <module id="log" class="System.Util.TLogRouter">
      <route class="Application.Common.MyEmailLogRoute" Levels="Warning, Error" />
    </module>
```

protected/Common/MyEmailLogRoute.php:
```php
Prado::using('System.Util.TEmailLogRoute')
class MyEmailLogRoute extends TEmailLogRoute
{
	/**
	 * Sends log messages to specified email addresses.
	 * @param array list of log messages
	 */
	protected function processLogs($logs)
	{
		$message='';
		foreach($logs as $log)
			$message.=$this->formatLogMessage($log[0],$log[1],$log[2],$log[3]);
		$message=wordwrap($message,70);
		foreach($this->_emails as $email)
		{
			// send email from $this->_from to $email
			// subject: $this->getSubject()
			// message: $message
		}
	}
}
```
