### ISSUE TITLE
Problem with redirect occured on Centos 7 

### ISSUE THREAD

**Issue by mrizkir** [pradosoft/prado#623]
Hello,

i got this problem again always on Centos OS with framework version 3.3.2, the page is blank and visitor cannot redirect to the Login page. We have the message on firebug. 

![problem_redirect](https://cloud.githubusercontent.com/assets/7402103/21351212/06bb6eb4-c6ee-11e6-8b5b-862c67b30852.PNG)

**Comment by ctrlaltca** [comment]
`401 Unauthorized` could mean either the virtualhost or the .htaccess configuration is incorrect or requires user authentication.

**Comment by mrizkir** [comment]
ok thanks, i try to check out configuration

**Comment by marioferj** [comment]
Hi,
To me also the same problem, a blank page and does not redirect to the login page.
If I remove the _**protected/pages/config.xml**_ file it works correctly.

**config.xml**
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <authorization>        
        <allow roles="admin,user" />
        <deny users="?" />
    </authorization>
</configuration>`

![image](https://cloud.githubusercontent.com/assets/15146171/21378410/ccee97d8-c70b-11e6-9f28-264e3d484085.png)

**Comment by ctrlaltca** [comment]
@marioferj a blank page typically means a php error. Check your web server's error log for hints.

**Comment by ctrlaltca** [comment]
Please reopen if you find the specific error that-s causing this issue.
