### ISSUE TITLE
friendly-url HiddenPath

### ISSUE THREAD

**Issue by Airakath** [pradosoft/prado#624]
Hello,
I've come across a problem when I put this config into the application.xml, the redirection is done as I want without the "index.php" but prado makes a 404 error. I think it's due to the lack of "Index.php" but I would like to make it work without this one.
```
     <module id="request" class="THttpRequest" UrlFormat="HiddenPath" UrlManager="friendly-url" />
      <module id="friendly-url" class="System.Web.TUrlMapping" EnableCustomUrl="true">

        <url ServiceParameter="Frontend.Accueil.Accueil" pattern="Accueil" />
```

**Comment by ctrlaltca** [comment]
HiddenPath requires a proper htaccess in order to work, something like:
```
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php/$1 [L]
```

**Comment by Airakath** [comment]
thank you very much ! It works perfectly!

**Comment by Airakath** [comment]
This htaccess works perfectly in localhost, but not on my shared server. I have no error of the server just a File not found ... I have a tutorial on the url rewriting but I do not see from where I could get the problem

`Options +FollowSymlinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php/$1 [L]`

**Comment by ctrlaltca** [comment]
Either your shared server is not running apache, or the htaccess is not being loaded (hint: [AllowOverride All](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride)

**Comment by Airakath** [comment]
thank you very much for your help.
