### ISSUE TITLE
Wrong action attribute value when using prado.php instead of pradolite.php

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#626]
A `http://www.exelmpe.com` prefix is added on "action" attribute of default form when using prado.php instead of pradolite.php

**Comment by ctrlaltca** [comment]
Pradolite.php is the concatenation of prado.php and other php files from framework/, so i suppose the issue id not there.
The form's action url is retrieved starting from [$_SERVER](http://php.net/manual/en/reserved.variables.server.php)['REQUEST_URI'], you may want to investigate the contents of that php variable.
Without other info there's no way we can help.

**Comment by frkinta** [comment]
Please see `framework/Web/UI/TForm.php` in line 49

**Comment by ctrlaltca** [comment]
Did you manage to fix this issue?

**Comment by frkinta** [comment]
SORRY. I added it many month ago when trying to fix #610 issue. 
I hope the solution of the issue #625 will be the good one
