### ISSUE TITLE
 Continuity of prado?

### ISSUE THREAD

**Issue by Rodrigo82Araya** [pradosoft/prado#627]
Hello friends of meadow. I commented that I work with its excellent framework. But I am interested in knowing if they continue updating it, since I have several projects on the way and I am interested in having an updated framework.
Thank you very much.

**Comment by ctrlaltca** [comment]
You can see latest development here: https://github.com/pradosoft/prado/commits/master

**Comment by mcinp** [comment]
What is the roadmap or any discussion on the framework?
I see version 4 in preparation, but no word on what is planned.

**Comment by ctrlaltca** [comment]
V4 is basically namespace + composer native support.
Discussions typically happens on github issues or on gitter: https://gitter.im/pradosoft/prado
