### ISSUE TITLE
Http 404 on documentation links at pradoframework.net

### ISSUE THREAD

**Issue by mcinp** [pradosoft/prado#628]
try
http://pradoframework.com/demos/quickstart/index.html
http://pradoframework.com/docs/classdoc/TActiveButton.html
or any link
e.g. blog tutorial doesn't display 404, but any page request end up on blog's home page

**Comment by ctrlaltca** [comment]
Pradoframework.com is not under our control. Please use pradoframework.net

**Comment by mcinp** [comment]
oh, it's time to go to optician I think ;) I don't even know how I got to this url, sorry for that
but I can see that my request to remove pradosoft.com from google search results is effective, as pradoframework.net appears as 1st result

**Comment by ctrlaltca** [comment]
Closing.
