### ISSUE TITLE
Missing #anchor on reload

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#630]
I changed the "helloword" script to.
```PHP
class home extends TPage {
    public function buttonClicked($sender, $param) {
        $this->Response->reload();
    }
}
```
When I click the button having like url `http://localhost/helloword/index.php#anchor`
The anchor disappear (most often) after refreshing.

**Comment by ctrlaltca** [comment]
The current anchor, meant as the current position of the browse scrollbar on the page, is something that only exists on the browser and never gets sent to the server in the http requests. You'll need some javascript magic to keep the current anchor valid between different page requests, eg: http://stackoverflow.com/questions/10612438/javascript-reload-the-page-with-hash-value
