### ISSUE TITLE
Can't set Transparent session ID to true

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#631]
When I set
```xml
<module id="session" class="THttpSession" SessionName="SSID" SavePath="/tmp"
        CookieMode="Allow" UseCustomStorage="false" AutoStart="true" GCProbability="1"
        UseTransparentSessionID="true" TimeOut="3600" />
```
 in `application.xml`, (as suggested here [http://pradosoft.github.io/docs/manual/class-THttpSession](http://pradosoft.github.io/docs/manual/class-THttpSession)) I have the following screen

![image](https://cloud.githubusercontent.com/assets/20577647/22109101/95882fd6-de56-11e6-8701-2a66873ebab3.png)

My problem is that I have many link referenced on search engine lke `http://www.example.com/index.php/?SSID=pdvocl7e6jc3kaodcktvn3fp17` and I don't want the SessionID to appear

**Comment by ctrlaltca** [comment]
You state that you set `CookieMode="Allow"` in the config, but the error states that the current value is `CookieMode="Only"`.
Either the config is not what you write or it's being changed somewhere in the code.

**Comment by frkinta** [comment]
I have this problem since many release. 
The reason is in the code. _I may be wrong but it look like `getCookieMode()` is executed before `setCookieMode($value)`._

**Comment by frkinta** [comment]
The default return value of `getCookieMode()` is `THttpSessionCookieMode::Only` when `setCookieMode()` is not yet executed

**Comment by ctrlaltca** [comment]
I made some quick tests adding the config from your first post:
```xml
<module id="session" class="THttpSession" SessionName="SSID" SavePath="/tmp"
        CookieMode="Allow" UseCustomStorage="false" AutoStart="true" GCProbability="1"
        UseTransparentSessionID="true" TimeOut="3600" />
```
inside the "personal" demo on prado-3.3.
It worked, so i added some debugging code in `THttpSession.php` to understand the order methods are called, and here's the result:
```
THttpSession::setCookieMode(Allow)
THttpSession::setUseTransparentSessionID(true)
THttpSession::init()
THttpSession::open()
```

So, i'm out of ideas; you may want to try to add some debug `echo()` or `error_log()` to THttpSession and see what's going on.

**Comment by frkinta** [comment]
I've try some thing. When I change the order of `CookieMode` and `UseTransparentSessionID` in declaration, the result is different:

`CookieMode="Allow" UseTransparentSessionID="true"` => no error
`UseTransparentSessionID="true" CookieMode="Allow"` => error

**Comment by ctrlaltca** [comment]
So the order of the parameters is important.
It seems like the example in http://pradosoft.github.io/docs/manual/class-THttpSession is using the correct order of parameters, but still we may want to state explicitly in the documentation of `setUseTransparentSessionID()` that  `CookieMode` must be changed _before_ enabling it.
