### ISSUE TITLE
Add component TActiveHtmlArea

### ISSUE THREAD

**Issue by zendre4** [pradosoft/prado#633]
Hello,

I remark than the active component of "THtmlArea4" was'nt implemented...

Can you implement this ?

Thanks

**Comment by frkinta** [comment]
I think it is in the framework. Take a look on the following link: 
[http://pradoframework.net/demos/quickstart/?page=Controls.HtmlArea4](http://pradoframework.net/demos/quickstart/?page=Controls.HtmlArea4)

**Comment by Airakath** [comment]
Yes it's true you are right. I personally use a TActivePanel which encompasses the THtmlArea4 to parlay the lack. And I ask for a reminder with
$ This-> TActivePanel-> render ($ param-> NewWriter);

**Comment by LCSKJ** [comment]
I will push the implementation of TActiveHtmlArea and TActiveHtmlArea4 to master shortly. Both controls provide the possibility to set new WYSIWYG editor content by calling setText() during callback. I will also push new quickstart tutorial pages to prado-demos demonstrating the usage during callback.

Feel free to test the new controls and don't forget to report bugs.
