### ISSUE TITLE
Performance tracing

### ISSUE THREAD

**Issue by deto1986** [pradosoft/prado#634]
Hi guys,

is there any mechanism to trace the performance of the framework while loading a site? Currently we having the issue that our site is loading about 4-5 seconds but not much data are requested. I would like to know where the hangtime is coming.

Regards,
Patrick

**Comment by ctrlaltca** [comment]
I suppose you may want to profile your application. I typically use [xdebug](https://xdebug.org/) to collect profiling data, that can be analyzed using [webgrind](https://github.com/jokkedk/webgrind)
A small introduction: http://www.rdeeson.com/weblog/163/profiling-php-using-xdebug-and-webgrind
Note: don't do this in production.

**Comment by deto1986** [comment]
Hey, thank you for the info. I was able to find the hangtime with webgrind. Thanks!

**Comment by ctrlaltca** [comment]
You are welcome 👍
