### ISSUE TITLE
Select multiple file in TFileUpload

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#635]
Hello,

With HTML5 it is possible to select multiple file in a single input `<input type="file" name="image" multiple="multiple" />`. Unfortunately it is _not yet_ working with `TFileUpload`. 
Can we expect something in the new release?

**Comment by LCSKJ** [comment]
That would be a nice feature indeed, give me some time and I will implement it for the upcoming PRADO4 release.

**Comment by LCSKJ** [comment]
I just finished implementation and will push it to master shortly. This enhancement adds HTML5 multiple file upload support for both `TFileUpload` and `TActiveFileUpload`. I also added a new block to the quickstart demos for both controls demonstrating the new multi file upload behavior.

The new feature is backward compatible and does not break old code if `setMultiple()` is kept unchanged. If set to true, the new behavior will kick in and multiple files can be selected in open file dialog.

Feel free to test it and don't forget to report bugs.

**Comment by ctrlaltca** [comment]
Awesome, big thumb up 👍

**Comment by frkinta** [comment]
Thanks,
In the same way a "`TFileValidator`" will be great since HTML5 allow to have some basic informations of files (size, mime, extension,...) locally on the browser. The validator will check each input file :
- size against `TFileUpload->MaxFileSize`  
- type/name against `TFileUpload->Accept` or `TFileUpload->Attributes.accept`.

In case of multiple file, the validator may indicate the names of files not valid.

What do you think about?
