### ISSUE TITLE
How can I set a validator when interacting with DataGrid

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#637]
Following that example [Interacting with TDataGrid](http://www.pradoframework.net/demos/quickstart/?page=Controls.Samples.TDataGrid.Sample3). 
How can I set a validator to a `TBoundColumn` or other input edited?
How can I set `Save` button as `DefaultButton` when an input have the focus?

**Comment by ctrlaltca** [comment]
> How can I set a validator to a TBoundColumn or other input edited?

You can't; you can use a TTemplateColumn and add the validator alongside the control.

> How can I set Save button as DefaultButton when an input have the focus?

This is not officially supported by now, but it would be a nice addition.

**Comment by frkinta** [comment]
Thanks, working well for TTemplateColumn but missing save button as default button. Hope it will be added soon.
