### ISSUE TITLE
Selecting item in TJuiAutoComplete after validation error

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#638]
I added the following code to that [`Home.page`](http://www.pradoframework.net/demos/quickstart/?page=ViewSource&path=/JuiControls/Samples/TJuiAutoComplete/Home.page).
```html
<com:TTextBox ID="txtDep" />
<com:TRequiredFieldValidator ValidationGroup="val" Display="Dynamic" FocusOnError="true" ControlToValidate="txtDep" Text="Fill the textbox" />
<com:TButton Text="send" ValidationGroup="val" />                
```
When the page is loaded and you FIRST click on the button, the `JuiAutoComplete` don't work again even after requirement satisfy.

**Comment by ctrlaltca** [comment]
The problem seems caused by the `FocusOnError` stealing the focus from the autocomplete when the suggestion list opens.

**Comment by ctrlaltca** [comment]
#639 should fix the issue, but i'd like to investigate a more proper solution before committing it.

**Comment by ctrlaltca** [comment]
So, the problem has been introduced in 98d37be0f614da4e1fb73e2ee3bb5bea437bcb5f.
The idea was to make `Prado.Element.focus` wait for all callbacks to finish before focusing the element, but instead it will force a focus on the element when every callbacks finishes, even future callbacks that have not started yet.
Properly fixing `Prado.Element.focus` will fix this issue

**Comment by ctrlaltca** [comment]
Proper fix is in place.

**Comment by frkinta** [comment]
Thank you
