### ISSUE TITLE
Firefox restores hidden field value after callback on F5-Reload

### ISSUE THREAD

**Issue by LCSKJ** [pradosoft/prado#642]
Found with FF 52.0.2, after doing some research this seems to be an issue for quite some time though.

Steps to reproduce:
- Go to the TActiveLabel quickstart tutorial
- Click the "click me" button
- Label is changing to "You clicked the button, didn't you?"
- Hit F5 key to reload the page
- Label is reverted to initial state "This is a label"
- Click the "click me" button again

Expected result:
- The F5 key should have fired a normal request rendering a new PRADO_PAGESTATE in the hidden field
- After hitting the "click me" button again, the label should change to "You clicked the button, didn't you?" again

Actual result:
- The F5 key fired a normal request but keeping the old PRADO_PAGESTATE on client side from the last callback
- After hitting the "click me" button again, the label does not change anymore

This behavior with TActiveLabel is just a demonstration (which comes from cc53959 since the viewstate value is identical to the new value if the pagestate is restored using F5 reload), but the problem is a global one with a quite big potential to cause side effects using callbacks in FF.

Every change to values in page-/viewstate during callback are kept and restored after a F5 reload in Firefox since it is restoring input fields where hidden ones belong to. Since PRADO is using a hidden field to pass the current state to following requests this may end up having an "unstable" state after using F5 to reload a page.

After some testing I can make these assumptions:
- only affects FF, IE/Edge and Chrome behave "correctly"
- looking at the response, PRADO renders a new pagestate on hitting F5, but somehow FF ignores it; running `$('#PRADO_PAGESTATE').val()` returns the old pagestate
- hitting enter in address bar or using CRTL+F5 to force a cache flush make it also work in FF
- only affects AJAX requests, hitting F5 after a postback asks to send form data again; this is intended behavior

I found some "solutions" digging the web, the best and easiest way is to add `autocomplete="off"` to the hidden field which prevents FF to restore the old value ... I tested it and it works correctly in all major browsers - not sure if it is W3C complaint though. If applicable , the fix needs to be applied to the `renderHiddenFieldsInt()` method within `TClientScriptManager` in line 903 (and maybe line 899) adding a `autocomplete="off"` to the hidden field.

Thoughts on this?

**Comment by ctrlaltca** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=520561
Sounds like the typical mozilla bug: reported 8 years ago, still no solution.

As far as i understand the `autocomplete="off"` solution works, but W3C doesn't allow that attribute on hidden fields.
I see two possible workarounds:
 1. change it with an `<input type="text" style="display: none;" autocomplete="off" />`
 2. drop the `<input />` tag and save the pagestate in a `<div />` or similar, and add some js code that adds the pagestate value to the form when posted. But this could potentially break fallback when js is not available.

**Comment by LCSKJ** [comment]
I'd tend to vote for your first solution for given reasons ... the change in `TClientScriptManager` will affect some other controls registering a hidden field though (like TFileUpload, TTabPanel etc.) - don't think it'll break anything, but just to mention it.
Just saw that the hidden fields are wrapped in a div with visibility:hidden, for what reason is this?

**Comment by ctrlaltca** [comment]
> Just saw that the hidden fields are wrapped in a div with visibility:hidden, for what reason is this?
Introduced here: f39661c02e0686848c01017fc51f1cd2ad714909
Then fixed here: df65c8daa6ec21c3cd8fe698e7d27d489200173e
No reason stated, anyway. But that was 2007, i suppose that some IE version wrongly rendered input fields and they had to add that workaround? Like https://csscreator.com/node/20467

**Comment by LCSKJ** [comment]
> Introduced here: f39661c
Then fixed here: df65c8d
No reason stated, anyway. But that was 2007, i suppose that some IE version wrongly rendered input fields and they had to add that workaround? Like https://csscreator.com/node/20467

Ah, OK, thanks.

I must admit that I'm still having gut feelings with this fix, can't name it directly but somehow it feels wrong to replace an element which is designed for such a use case with another element intended for different tasks just for a single browser (even if FF is widespread).
Since I'm in need of a solution though because our QA/support team will not accept such a behavior for end uses, I may end up making a local fix for now ... although I think it should be addressed in PRADO framework.

We may leave this open for some time, maybe someone has a better idea ... if not, I will apply this patch to master in some days.

**Comment by ctrlaltca** [comment]
Another possibility: randomize the hidden field name so that browsers won't cache it.
After digging on this option, i'd discard it because:
 * we should keep track of the randomized name
 * changing the hidden field name at every callback is troublesome (parallel ajax calls?)
 * it will break controls using `registerHiddenField()` and updating the field from clientside

**Comment by ctrlaltca** [comment]
Any possible method using js, like eg. storing the original value somewhere or renaming the "value" attribute and restoring it just before form submit, will fail if javascript is not enabled, so these are discarded, too.

**Comment by LCSKJ** [comment]
For now we implemented a workaround only for pagestate rendering it in an invisible text input in our project ... deriving TClientScriptManager is a pain though since it's all private, so our "fix" is more a dirty hack. I'd love to see a clean fix in PRADO so we can remove it later.

**Comment by ctrlaltca** [comment]
So, rendering `<input type="text"` instead of `<input type="hidden"` at https://github.com/pradosoft/prado/blob/master/framework/Web/UI/TClientScriptManager.php#L899 is probably the easier solution.
Of course we need to ensure that those controls are not visible and doesn't break the page layout.
We could just hide their container div using`display:none`, but this seems to cause issues with old browsers. This is probably where the `visibility:hidden` came from, see related discussion at http://stackoverflow.com/questions/8318428/submit-form-fields-inside-displaynone-element

**Comment by LCSKJ** [comment]
I don't have an old enough browser that has issues with posting invisible form fields. In our solution I put a `display:none` on the text input itself too ... that may cause trouble in older browser though (which we just ignore in our case :smile:).
Maybe it's OK to use CSS to reclaim the reserved space from `visibility:hidden`, like in the accepted post with `position:absolute` or `height:0px` or so ...

**Comment by ctrlaltca** [comment]
@LCSKJ if the fix you tested is working, fell free to commit it, thank you.

**Comment by LCSKJ** [comment]
The fix works, but as I wrote, we put a display:none on the input, so the wrapping `visibility:hidden` div does not take any space ... that may cause trouble with older browser though. I haven't tested using CSS instead yet, but I can try when I'm back at work on tuesday.
What is the preferred way, ignoring (potential) trouble with some older browers or fiddling around with CSS to reclaim blocked space?

**Comment by ctrlaltca** [comment]
Plan:
 1. adopt the `<input type="text" style="display:none" autocomplete="off" ` solution
 2. switch the default doctype from xhtml to html5 to avoid validation errors
 3. Fix code (demos, ...) to pass html validation (eg. removing `<meta http-equiv="content-language" content="en"/>` tags)

Is point 2 acceptable?

**Comment by LCSKJ** [comment]
I guess switching to HTML5 is reasonable nowadays.

**Comment by ctrlaltca** [comment]
So, i finally took the time to patch this. @LCSKJ can you please check if it looks good to you?
