### ISSUE TITLE
PRADO Tools

### ISSUE THREAD

**Issue by Airakath** [pradosoft/prado#643]
Hello

I have just realized that the links of "PRADO Tools

" has the address http://www.pradoframework.net/site/download its dead.

I have to keep aside the Textmate Bundle PRADO TextMate Bundle, also suitable for Sublime Text 2 (r3193) July 24, 2012.

(The bundle works very well on sublimtext 3)

I will deposit it if you shouaity put it back online for the community.

[prado-textmatebundle-r3193.zip](https://github.com/pradosoft/prado/files/935040/prado-textmatebundle-r3193.zip)

have a good day

**Comment by ctrlaltca** [comment]
Thank you!
Also, we should really create an automated way to create this bundle starting from the APIs..

**Comment by ctrlaltca** [comment]
So, the editor plugins were still available in the code.
I've created a new repository: https://github.com/pradosoft/editor-plugins for them, now it would be nice to update them providing support for the new prado controls introduced since their last update.

**Comment by ctrlaltca** [comment]
For your interest, i've started working on a SublimeText 3 native plugin: https://github.com/pradosoft/editor-plugins/tree/master/SublimeText

**Comment by ctrlaltca** [comment]
Page updated!
