### ISSUE TITLE
Problem with package bower-asset/scriptaculous-bower

### ISSUE THREAD

**Issue by LCSKJ** [pradosoft/prado#645]
The mentioned package is used by Prado as dependency in composer.json, loaded from bower through asset-packagist. The entry in composer.json looks like
```
"bower-asset/scriptaculous-bower": "^1.9"
```
If you require Prado in your own composer.json, it will fail installing with an error message saying that the package is missing. This even happens if you just require that package in an empty composer project. This only happens, if you make a clean install without using a stale state from composer.lock, since it will just use the 1.9.0 zip package from github.com then.

Since there was no change in Prado, we didn't change composer version, the packages at asset-packagist.org and at bower are looking good, I am not sure what may cause this.
I also already filed an issue at https://github.com/hiqdev/asset-packagist/issues/40 ... maybe they changed something at asset-packagist.

Reproduce with this `composer.json` in an empty folder running `composer install`
```
{
    "name": "test/test",
    "require": {
        "pradosoft/prado": "dev-master"
    },
    "repositories": [{
	"type": "composer",
	"url": "https://asset-packagist.org"
    }]
}
```

**Comment by LCSKJ** [comment]
Looks like this is an issue with asset-packagist, they already have a fix which is not yet merged and released ... once that happened I will close this issue.

**Comment by ctrlaltca** [comment]
I gave the issue a brief look yesterday but had no time to go deeper. Nice to see they already worked out a fix

**Comment by LCSKJ** [comment]
They fixed it in production, problem is gone - I'll close this issue.
