### ISSUE TITLE
Extend presentation of RadioButtonList

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#647]
Hello Guys,
_[This is not an issue]_
I'm trying to produce a radio button group within a html table. In the picture the result expected:
![image](https://cloud.githubusercontent.com/assets/20577647/26678453/835030ae-46c8-11e7-9831-71b65ba689dc.png)

`TRadioButtonList` is probably a good base to solve my problem but I have not enough skills to extend the it.

In [this sample](http://www.pradoframework.net/demos/quickstart/?page=Controls.Samples.TRepeater.Sample3) I've add a new table cell `<td><com:TRadioButton ID="RB" GroupName="RadioGroup" /></td>` but as result, the grouping name is not the same and therefore the selection may not be unique. 

How can I do it?

**Comment by ctrlaltca** [comment]
Have a look at http://pradosoft.github.io/docs/manual/class-TRadioButton.html#_setUniqueGroupName

**Comment by frkinta** [comment]
Thank you for the answer.
If I use `TRadioButton`s grouped within a Data Control (Repeater, DataList,...) how can I use a `TRequiredFieldValidator` for a each Group?

**Comment by ctrlaltca** [comment]
If i understand correctly what you mean, you actually can't, since `TRequiredFieldValidator ` needs to target a single `ControlToValidate`.
I'd use a TCustomValidator
