### ISSUE TITLE
Search on website dont work

### ISSUE THREAD

**Issue by GermanMech** [pradosoft/prado#654]
Link: http://www.pradoframework.net/demos/quickstart/?page=GettingStarted.Introduction

If you want to search something there pops up an error:

Zend_Search_Lucene_Exception
Description

Source File

/var/www/www.pradoframework.net/prado-demos/vendor/zf1/zend-search-lucene/library/Zend/Search/Lucene.php (297)

**Comment by ctrlaltca** [comment]
Fixed; I forgot to run the indexer script after an update, thank you for noticing!

**Comment by GermanMech** [comment]
Thanks for fixing so fast! can search now. :D
