### ISSUE TITLE
Error when try to load sample

### ISSUE THREAD

**Issue by GermanMech** [pradosoft/prado#655]
Link: http://www.pradoframework.net/demos/quickstart/index.php?page=Controls.Samples.TTextBox.Home

Error:

Prado\Exceptions\TInvalidOperationException
Description

Component 'Home' is evaluating an invalid expression '($this->TextBox2->SafeText)' : [User Warning] Directory /var/www/www.pradoframework.net/prado-demos/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 (@line 292 in file /var/www/www.pradoframework.net/prado-demos/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php)..
Source File

/var/www/www.pradoframework.net/prado-demos/vendor/pradosoft/prado/framework/TComponent.php (1259)

**Comment by ctrlaltca** [comment]
Thank you for the report; the fix was simple (chmod), but i took the steps to ensure this won't happen again in the future.

**Comment by GermanMech** [comment]
thanks for fix!
