### ISSUE TITLE
Wrong link into documentation in exceptions

### ISSUE THREAD

**Issue by PaznerA** [pradosoft/prado#657]
**For example:**
Unknown component type '[TForm2](http://pradosoft.github.io/docs/manual/class-TForm2)'. This may be caused by the following parsing error in the [TForm2](http://pradosoft.github.io/docs/manual/class-TForm2) class file:

**Comment by ctrlaltca** [comment]
Where are you getting this error? on the official documentation? or in a page inside your application?

**Comment by PaznerA** [comment]
In a page inside my application...  when trying use unknown <com:T>

**Comment by ctrlaltca** [comment]
So your problem is that no documentation exists for a not-existing component?
The error page tries to guess a documentation url for a component from its name.
You are trying to use a component named TForm2 that doesn't exists in Prado, so no documentation is available for it.

**Comment by PaznerA** [comment]
You're right. My fault. 
Thanks for quick response.
