### ISSUE TITLE
TCallback requests does not fill active controls

### ISSUE THREAD

**Issue by chetiv** [pradosoft/prado#659]
I have updated my project from Prado 3.1.7 to Prado 3.3.2 and seem that changing the active controls from Prototype to jQuery has badly changed the behavior of the application.

I have a list of items and, for each row, I have a button that should open a bootstrap dialog for editing the line. The dialog which is filled by a TCallback operation having as parameter the row identifier. When I open the dialog for the first time after the list was loaded, it is opened well. Next time when I try to open it (without refreshing the list page), the active controls are not filled correctly. The callback is executed correctly in php, but the values set on active controls are not set.

Do someone have any suggestions to solve this situation?

**Comment by ctrlaltca** [comment]
Please provide a basic example of the code that's not working for you.

**Comment by chetiv** [comment]
To provide an example is very complicated... but I have identified the problem. Seem that not the TCallback is the problem. A possible incompatibility between jQuery and Bootstrap (the versions available in Prado 3.3.2) seem to generate the problem.  Theoretically the bootstrap dialog is not closing well or I should add supplementary js code. The code that makes the modal to work correctly is:

$('#modal').on('hidden.bs.modal', function () {
	$(this).off();
});

**Comment by jcass77** [comment]
I think there might be potential jQuery conflicts as well.

When upgrading to PRADO v4.0.0, I removed the reference to the Bootstrap supplied version of jQuery via `TClientScript`, and then relied on `<com:TClientScript PradoScripts="jquery" />` to use the PRADO-supplied version.

Not sure what the situation with 3.3.2 is exactly though but probably some variation of the above.

**Comment by ctrlaltca** [comment]
Sorry i don't get exactly what you are meaning. Both the bootstrap and jQuery libraries are included in Prado using bower; the bootstrap library doesn't contain a copy of jQuery as far as i can see, in fact the first lines of bootstrap.js reads:
```js
if (typeof jQuery === 'undefined') {
  throw new Error('Bootstrap\'s JavaScript requires jQuery')
}
```
If there's some incompatibility i'll be glad to fix it!

**Comment by jcass77** [comment]
Sorry I got confused - I'm using a Bootstrap theme, not vanilla, that comes packaged with jQuery.

**Comment by ctrlaltca** [comment]
```
$('#modal').on('hidden.bs.modal', function () {
$(this).off();
});
```
You are removing all event handlers from the modal element after it gets hidden.
It sounds more like a workaround that a proper fix, the problem is caused by something else.
Feel free to reopen if you mind sharing a snippet of code causing the problem that can be used to debug and fix it.
