### ISSUE TITLE
PHP 7.2 warning messages break active controls

### ISSUE THREAD

**Issue by jcass77** [pradosoft/prado#663]
PHP 7.2 introduces a backward-incompatible change that issues a [warning when counting non-countable types](http://php.net/manual/en/migration72.incompatible.php).

This breaks PRADO's [`TCallbackPageStateTracker`](https://github.com/pradosoft/prado/blob/61fbd53bc1a71d4206edcc0eb1ba8d73a0466543/framework/Web/UI/ActiveControls/TCallbackPageStateTracker.php#L192), preventing active controls from being updated after postbacks (and probably causing issues in a few other places as well).

It looks like one is supposed to wrap everything in an `isset()` validation before calling `count()`, from here on out.

**Comment by ctrlaltca** [comment]
```
Searching 1023 files for "[^\$a-z_]count\s*\(" (regex)
227 matches across 90 files
```
It will be a long weekend :)

**Comment by ctrlaltca** [comment]
So, the fix for the main issue reported is already in master. I'll keep this open until i finish reviewing the rest of the code.

**Comment by ctrlaltca** [comment]
Another php 7.2 compatibility fix: https://github.com/pradosoft/prado/commit/1b68861ff986b28e761e45a21874030ad4d26c7a

**Comment by ctrlaltca** [comment]
Now that 4.0.1 is released with the fix,  think it's time to close this ticket, too.
