### ISSUE TITLE
Trepeater viewstate after post

### ISSUE THREAD

**Issue by frkinta** [pradosoft/prado#666]
May be something wrong with viewstate?

```PHP
	public function onLoad($param) {
		parent::onLoad($param);
		if (!$this->IsPostBack) {
			$this->repTest->setDataSource($this->Data);
			$this->repTest->dataBind();
		}
	}

	public function getData() {
		return [
		    ['key' => 'first', 'text' => 'First 01'],
		    ['key' => 'second', 'text' => 'Second 02'],
		    ['key' => 'third', 'text' => 'Third 03'],
		];
	}

	public function Click($sender, $param) {
		$this->lblReturn->Text = 'Clicked ' . time();
	}
```

```HTML
	<com:TRepeater ID="repTest" EnableViewState="true">
		<prop:ItemTemplate>
			<%# $this->Data['key']%> == <%# $this->Data['text']%>
		</prop:ItemTemplate>
	</com:TRepeater>
	<com:TLiteral ID="lblReturn" />
	<com:TButton Text="Click" OnClick="Click" />
```

When I click the button I have the TRepeater without the binded data as expected.
![image](https://user-images.githubusercontent.com/20577647/37088361-60c4dc04-21fd-11e8-9441-f553c4d6419f.png)
Is it the normal behaviour?

Tested on Prado 3.3

**Comment by ctrlaltca** [comment]
Yes, because you are databinding the actual data only on the first request (`if(!$this->IsPostBack)`).
The viewstate actually saves the UI controls and their attributes, but not the original data that has been databind()ed to the `TRepeater`

**Comment by frkinta** [comment]
meaning that I have to bind data on every request? 
Is it a way not to `dataBind()` again and again ... while on the same page?

**Comment by ctrlaltca** [comment]
If you want to avoid the text being lost, place it inside a control that saves its content in its viewstate, eg. a `TLIteral`:

```php
	<com:TRepeater ID="repTest" EnableViewState="true">
		<prop:ItemTemplate>
			<com:TLiteral Text="<%# $this->Data['key']%> == <%# $this->Data['text']%>" />
		</prop:ItemTemplate>
	</com:TRepeater>
```

**Comment by frkinta** [comment]
Thanks. Clear now
