### ISSUE TITLE
Wsat generating wrong urls

### ISSUE THREAD

**Issue by sicutdeux** [pradosoft/prado#668]
Everytime the Wsat has to render a New page, i get redirected to this kind of url:

wsat,TWsatGenerateAR

But if i use the proper url manually it works.

Version: latest composer project

**Comment by ctrlaltca** [comment]
Hi! I just tested creating a new project, adding this configuration to the application.xml:
```
<service id="wsat" class="System.Wsat.TWsatService" Password="pass">
  <modules>
    <module class="System.Data.ActiveRecord.TActiveRecordConfig" EnableCache="true">
      <database ConnectionString="mysql:host=localhost;dbname=db" Username="user" Password="pass" />
    </module>
  </modules>
</service>
```
And I can then login to Wsat and generate the ActiveRecord classes correctly.
The url of the page used to generate the classes is indeed `http://127.0.0.1/testapp/wsat,TWsatGenerateAR`, where testapp is the name of the folder containing the test application.
The request module should be able to understand that "wsat" is a service name and "TWsatGenerateAR" is the requested page name for that service, and it seems to work here.
Can you please add some more details about your problem?

**Comment by darthdaniel85** [comment]
Hi Fab, its been a long time... but Im back, this time from Los Angeles, USA. Glad to see that quite a few people are using WSAT. I will make some time to continue supporting Prado... also glad to see that you are still keeping the framework alive, thats remarkable. Greetings Daniel(WSAT creator)

**Comment by ctrlaltca** [comment]
@sicutdeux did you manage to fix your issue?

**Comment by ctrlaltca** [comment]
No news is good news, i suppose.
Pleas reopen if you still have this problem.
