### ISSUE TITLE
Internationalization (I18N) and Localization (L10N)

### ISSUE THREAD

**Issue by Airakath** [pradosoft/prado#670]
Hello,
The translate does not work in prado objects but works in standard html tags.

I specify I am using prado 4

example  not working:

`					<com:TLinkButton 	
						OnClick="linkButtonCategolrie_Clicked" 
						CssClass="linkFilDAriane" 
						Text="<%[Utilisateurs]%>" 
					/> `

working: 
`<h3 class="sub-header page-header"><%[ Gestionnaire d'utilisateur ]%></h3>`

**Comment by ctrlaltca** [comment]
Hi! Sorry but i can't speak french.
I use the I18N tags in a lot of projects, and i can assure that they are working inside control properties aswell. Can you provide an example file showing the problem?

**Comment by Airakath** [comment]
`<%@ MasterClass="Application.layouts.MainLayoutAdmin" Title="Users - Utopia Script" %>


<com:TContent ID="pageHeader">

	<div class="fildArianne">
		<nav aria-label="vous etes ici:" role="navigation">
			<ul class="breadcrumbs positionBreadCrumbs">
				<li>
					<com:TLinkButton 
						Text="<%[ Administration ]%>" 
						OnClick="linkButtonCategolrie_Clicked" 
						CssClass="linkFilDAriane" 
					/> 
				</li>
					
				<li>
					<com:TLinkButton 	
						OnClick="linkButtonCategolrie_Clicked" 
						CssClass="linkFilDAriane" 
						Text="<%[Utilisateurs]%>" 
					/> 
				</li> 					
			</ul>				
		</nav>
		<h3 class="sub-header page-header"><%[ Gestionnaire d'utilisateur ]%></h3>
	</div>	
  	
</com:TContent>

<com:TContent ID="contenu">

  	<div class="blockModule">      			
		<com:CrudRecord id="crud"/>
	</div>

									
	<script type="text/javascript">
		jQuery("#administration").addClass("activeBtnDropdown");
		jQuery("#administration").next().addClass("activetedDropDown");
		jQuery("#ctl0_linkButtonUtilisateursAdministration").addClass("HoverMenu");	
	</script>	

</com:TContent>`

`
	    <using namespace="System.I18N.*"/>

		<module id="globalization" class="TGlobalization" DefaultCulture="fr" TranslateDefaultCulture="false">
		    <translation type="XLIFF"
		        source="Application.Translate.messages"
		        marker="@@"
		        autosave="true" cache="true" />
		</module>
`

**Comment by Airakath** [comment]
in my code the translation works but not in the property Text example
Text = "<% [Administration]%>

**Comment by Airakath** [comment]
hi testing, but i don't understand 
test.php
`		$this->getApplication()->getGlobalization()->setDefaultCulture('fr_FR');
		p($this->getApplication()->getGlobalization()->getDefaultCulture());
		
		$this->getApplication()->getGlobalization()->setCulture('fr_FR');
		p($this->getApplication()->getGlobalization()->getCulture());
		
		p($this->getApplication()->getGlobalization()->getLocalizedResource('Application.Translate.messages'));


		p($this->getApplication()->getGlobalization()->getTranslateDefaultCulture());
		p($this->getApplication()->getGlobalization()->getTranslationConfiguration());
		p($this->getApplication()->getGlobalization()->getTranslationCatalogue());
		p($this->getCurrentCulture());
		
		p($this->getApplication()->getGlobalization()->getCharset());

	}

    public function getCurrentCulture()
    {
        $culture = $this->getApplication()->getGlobalization()->getCulture();
        $cultureInfo = new CultureInfo($culture);
        return $cultureInfo->getNativeName();
    }`
test.page
string(5) "fr_FR"
string(5) "fr_FR"
Array
(
    [0] => .\fr_FR\Application.Translate.messages
    [1] => .\fr\Application.Translate.messages
    [2] => .\Application.Translate.fr_FR.messages
    [3] => .\Application.Translate.fr.messages
    [4] => Application.Translate.messages
)
bool(true)
object(Prado\Collections\TMap)#20 (6) {
  ["_d":"Prado\Collections\TMap":private]=>
  array(5) {
    ["type"]=>
    string(5) "XLIFF"
    ["source"]=>
    string(61) "C:\wamp\www\PRADO\AppolonBioteck\protected\Translate\messages"
    ["marker"]=>
    string(2) "@@"
    ["autosave"]=>
    string(4) "true"
    ["cache"]=>
    string(77) "C:\wamp\www\PRADO\AppolonBioteck\protected\runtime\application.xml-4.0.1/i18n"
  }
  ["_r":"Prado\Collections\TMap":private]=>
  bool(false)
  ["_e":"Prado\TComponent":private]=>
  array(0) {
  }
  ["_listeningenabled":"Prado\TComponent":private]=>
  bool(false)
  ["_behaviorsenabled":"Prado\TComponent":private]=>
  bool(true)
  ["_m":"Prado\TComponent":private]=>
  NULL
}
NULL
string(18) "français (France)"
string(5) "UTF-8"

because my message.xml is 

```
<?xml` version="1.0" encoding="UTF-8"?>
<xliff version="1.0">
 <file source-language="FR_fr" target-language="en" datatype="plaintext" original="messages" date="2018-06-05T12:07:23Z" product-name="messages">
  <body>
  
<trans-unit id="1">
<source><![CDATA[Salut]]></source>
<target><![CDATA[Hi]]></target>
</trans-unit>

<trans-unit id="2">
<source><![CDATA[Campagne de Mailling]]></source>
<target><![CDATA[Email campaign]]></target>
</trans-unit>
</body>
 </file>
</xliff>

```

working in this way my text is still translated when it should not. In addition I made tests and removing TranslateDefaultCulture = "false" the translation works in the properties of prado Text object.

**Comment by ctrlaltca** [comment]
Looking at the fact that enabling "TranslateDefaultCulture" fixes the problem, i guess that's something related to different cultures being used.
Can you try to use the same culture on all files, eg.:

application.xml
```
<module id="globalization" class="TGlobalization" DefaultCulture="fr_FR" TranslateDefaultCulture="false">
```

messages.xml:
```
<file original="I18N Example IndexPage" source-language="fr_FR" datatype="plaintext" date="2018-06-04T16:53:18Z">
```


Ans see if it works then?

**Comment by Airakath** [comment]
I try but I have a probleme, if i adding TranslateDefaultCulture="false", the propertise text on prado object isn't translate

**Comment by Airakath** [comment]
messages.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.0">
 <file source-language="fr_FR" target-language="en" datatype="plaintext" original="messages" date="2018-06-05T12:07:23Z" product-name="messages">
  <body>
  
<trans-unit id="1">
<source><![CDATA[Salut]]></source>
<target><![CDATA[Hi]]></target>
</trans-unit>

<trans-unit id="2">
<source><![CDATA[Campagne de Mailling]]></source>
<target><![CDATA[Email campaign]]></target>
</trans-unit>
</body>
 </file>
</xliff>
```
test.php
```
		$this->getApplication()->getGlobalization()->setDefaultCulture('fr_FR');
		p($this->getApplication()->getGlobalization()->getDefaultCulture());
		
		$this->getApplication()->getGlobalization()->setCulture('en');
		p($this->getApplication()->getGlobalization()->getCulture());
		
		p($this->getApplication()->getGlobalization()->getLocalizedResource('Application.Translate.messages'));


		p($this->getApplication()->getGlobalization()->getTranslateDefaultCulture());
		p($this->getApplication()->getGlobalization()->getTranslationConfiguration());
		p($this->getApplication()->getGlobalization()->getTranslationCatalogue());
		p($this->getCurrentCulture());
		
		p($this->getApplication()->getGlobalization()->getCharset());

	}

    public function getCurrentCulture()
    {
        $culture = $this->getApplication()->getGlobalization()->getCulture();
        $cultureInfo = new CultureInfo($culture);
        return $cultureInfo->getNativeName();
    }
```
application.xml

```
		<module id="globalization" class="TGlobalization" DefaultCulture="fr_FR" TranslateDefaultCulture="false">
		    <translation type="XLIFF"
		        source="Application.Translate.messages"
		        marker="@@"
		        autosave="true" cache="true" />
		</module>

```

test.page
```

		<h3 class="sub-header page-header"> <%[Campagne de Mailling]%> </h3>
		<com:TLabel ID="label1" Text="<%[ Salut ]%>" />
```

result text.page

string(5) "fr_FR"
string(2) "en"
Array
(
    [0] => .\en\Application.Translate.messages
    [1] => .\Application.Translate.en.messages
    [2] => Application.Translate.messages
)
bool(false)
object(Prado\Collections\TMap)#20 (6) {
  ["_d":"Prado\Collections\TMap":private]=>
  array(5) {
    ["type"]=>
    string(5) "XLIFF"
    ["source"]=>
    string(61) "C:\wamp\www\PRADO\AppolonBioteck\protected\Translate\messages"
    ["marker"]=>
    string(2) "@@"
    ["autosave"]=>
    string(4) "true"
    ["cache"]=>
    string(77) "C:\wamp\www\PRADO\AppolonBioteck\protected\runtime\application.xml-4.0.1/i18n"
  }
  ["_r":"Prado\Collections\TMap":private]=>
  bool(false)
  ["_e":"Prado\TComponent":private]=>
  array(0) {
  }
  ["_listeningenabled":"Prado\TComponent":private]=>
  bool(false)
  ["_behaviorsenabled":"Prado\TComponent":private]=>
  bool(true)
  ["_m":"Prado\TComponent":private]=>
  NULL
}
NULL
string(7) "English"
string(5) "UTF-8"

Email campaign
Salut

**Comment by Airakath** [comment]
I think there is a problem with TranslateDefaultCulture = "false"

**Comment by Airakath** [comment]
if I use TranslateDefaultCulture = "false" this gives me on the show Salut page
and if I take it off it gives me @@ Salut @@

this means that the translation did not take into account in the prado object when I use TranslateDefaultCulture = "false". I think there is a problem in this function

moreover, in the property in Text do not have autosave

**Comment by ctrlaltca** [comment]
So, i took your initial example and modified the helloworld demo including its code; the result code is attached.
[helloworld.zip](https://github.com/pradosoft/prado/files/2072419/helloworld.zip)

I've tried translating both to `fr_FR` and `en` and it works fine.
Does it work for you?
If it does => it's probably because of something else that we need to investigate inside you app
If it doesn't => it's probably caused by some external factor, eg. php/apache version, os, etc..

**Comment by Airakath** [comment]
Thank you I tested. It works since I added in .page
<%@  Application.Globalization.Culture="en"  %>

but I would have liked to declare it in php for dynamic rendering in my application
```
	public function onInit($param){

		parent::onInit($param);
		
		$this->getApplication()->getGlobalization()->setCulture('en');
}
```
thank you very much for your very precious help

**Comment by ctrlaltca** [comment]
I suppose that `onInit()` happens too late during the page load to work.
You can try to set the culture inside `onPreInit()`, but i'm not 100% sure it will work either; `__construct()` will work, but it's ugly.
I normally add a module that handles setting the right culture, since module initialization happens at a very early stage. Maybe it can be useful:

```xml
<module id="globalization" class="Application.Common.MyGlobalizationAutoDetect" charset="UTF-8" DefaultCulture="en" TranslateDefaultCulture="false" AvailableLanguages="en, it">
```

```php
class MyGlobalizationAutoDetect extends Prado\I18N\TGlobalization
{
	private $_detectedLanguage;
	private $_validLangs;

	public function init($xml)
	{
		parent::init($xml);
		//set the culture according to browser language settings
		$http = new Prado\I18N\core\HTTPNegotiator();
		$languages = $http->getLanguages();
		foreach($languages as $lang)
		{
			$mainLang = strstr($lang, '_', true);
			if(!in_array($mainLang, $this->_validLangs))
				continue;

			$this->_detectedLanguage=$mainLang;
			$this->setCulture($mainLang);
			return;
		}
	}

	public function getDetectedLanguage()
	{
		return $this->_detectedLanguage;
	}

	/**
	 * Get the available languages.
	 * @return array of languages
	 */
	public function getAvailableLanguages()
	{
		return $this->_validLangs;
	}

	/**
	 * Set the available languages.
	 * @param Comma separated string of available languages.
	 */
	public function setAvailableLanguages($langs)
	{
		$this->_validLangs = array_map('trim', explode(',', $langs));
	}
}
```

**Comment by Airakath** [comment]
thank you that's it! it works !
good job ! 👍
