### ISSUE TITLE
cookie example 

### ISSUE THREAD

**Issue by Airakath** [pradosoft/prado#672]
Hello,
I try to use a cookie to store the products of a cart. but I can not give a date of hope to the cokkie. I did not find his information in the doccumentations

I would like to know if I need to generate a new cookie or if I can use the session cookie ?

could anyone give me an example of what I could support

application xml
``
<module id="request" class="THttpRequest" UrlFormat="HiddenPath" UrlManager="friendly-url" EnableCookieValidation="true"/>
<module id="session" class="THttpSession" SessionName="SSID" CookieMode="Only" UseCustomStorage="false" AutoStart="true" TimeOut="28800" />
``

thank you in advance

**Comment by ctrlaltca** [comment]
Prado uses a cookie to identify an user and keep his session information, but persistent data is usually saved inside the php session or in the page viewstate.
You may want to have a read at http://pradoframework.net/demos/quickstart/?page=Advanced.State , if you didn't already.

**Comment by Airakath** [comment]
thank you i'm going to look

**Comment by ctrlaltca** [comment]
Closing. Feel free to reopen if further discussion is needed.
