### ISSUE TITLE
Nested active repeaters problem

### ISSUE THREAD

**Issue by szroman** [pradosoft/prado#676]
Hi,

After pressing button i get this message:

> Component event 'Prado\Web\UI\ActiveControls\TActiveRepeater.onitemcreated' is attached with an invalid event handler 'Page.OnInnerItemCreated

```html
<com:TActiveButton Text="Button" OnClick="ButtonClicked" />

<com:TActiveRepeater
    ID="Outer"
    OnItemCreated="Page.OnOuterItemCreated"
    DataKeyField="id">
    <prop:ItemTemplate>

        <com:TActiveLabel Text="<%# $this->Data['name'] %>" />

        <com:TActiveRepeater
            ID="Inner"
            OnItemCreated="Page.OnInnerItemCreated"
            DataKeyField="id">
            <prop:ItemTemplate>
                <com:TActiveLabel Text="<%# $this->Data['name'] %>" />
            </prop:ItemTemplate>
        </com:TActiveRepeater>

    </prop:ItemTemplate>
</com:TActiveRepeater>
```

```php
class Home extends BasicPage
{
        public function getData()
	{
		$data = array();
		$data[] = array('id' => 1, 'name' => 'a');
		$data[] = array('id' => 2, 'name' => 'b');
		$data[] = array('id' => 3, 'name' => 'c');

		return $data;
	}

	public function ButtonClicked($sender, $param)
        {
		$this->Outer->DataSource = $this->getData();
		$this->Outer->dataBind();
        }

	public function OnOuterItemCreated($sender, $param)
        {
            $item = $param->Item;

            if ($item->ItemType === 'Item' || $item->ItemType === 'AlternatingItem' || $item->ItemType === 'SelectedItem')
            {
			$item->Inner->DataSource = $this->getData();
			$item->Inner->dataBind();
            }
        }

	public function OnInnerItemCreated($sender, $param) {}
}
```

**Comment by ctrlaltca** [comment]
From http://pradosoft.github.io/docs/manual/class-Prado.Web.UI.WebControls.TRepeater.html#_onItemCreated:

> ﻿﻿Raises OnItemCreated event. This method is invoked after a repeater item is created and instantiated with template, but **before** added to the page hierarchy. The repeater item control responsible for the event can be determined from the event parameter.

SInce `OnItemCreated` is called before the item is actually added to the page, items inside the `Outer` repeater will have no `Page` property set at that time.

You can easily fix this problem using the `OnItemDataBound` event handler in place of `OnItemCreated` in the `Outer` repeater.

**Comment by szroman** [comment]
Thanks for your help and quick response. I suggest applying this also to example of [nested repeaters](http://www.pradoframework.net/demos/quickstart/?page=ViewSource&path=/Controls/Samples/TRepeater/Sample2.page)
from The QuickStart Tutorial.

**Comment by ctrlaltca** [comment]
Added some comments here:  https://github.com/pradosoft/prado-demos/commit/8a2687268aba8cf9d65a44d460cadd3e172715dd
