### ISSUE TITLE
Sorting on TActivedataGrid is not working on TTemplateColumn

### ISSUE THREAD

**Issue by jo49bimpf** [pradosoft/prado#681]
Hello,

the sorting on TActivedataGrid is not working on TTemplateColumn isn't working in 3.3.3 with php7.
This is the page setup:

<com:TActiveDataGrid
					ID="VersionGrid" 
					DataKeyField="ID" 
					AllowPaging="True" 
					AutoGenerateColumns="false" 
					PageSize="40" 
					PagerStyle.Mode="Numeric" 
					PagerStyle.HorizontalAlign="Left" 
					ItemStyle.BackColor = "#BFCFFF" 
					AlternatingItemStyle.BackColor = "#E6ECFF"
					HeaderStyle.Backcolor="#e6eaf5" 
          			OnItemCreated="VersionCreated" 
					OnPageIndexChanged="changePage" 
					OnPagerCreated="pagerCreated"
					OnPreRender ="PreRender" 
					AllowSorting="true" 
					OnSortCommand="sortDataGrid"
				    >

...

			        <com:TTemplateColumn 
                        SortExpression="Module" 
                        ID="Moduleht" 
                        HeaderText="Module" 
                        HeaderStyle.CssClass="sort-arrow" 
			ItemTemplate="<%# $this->Parent->Data->Module %>"
                        >
    		        	<prop:Headertemplate>
	                        <com:TLinkButton 
                                Text="Module" 
                                CommandName="Sort" 
                                CommandParameter="Module" 
                                CausesValidation="false" 
                                Tooltip="Module wird momentan nur im C/S Bereich gefüllt."
                                  />
                            <br> 
	                        <div>
                                <com:TActiveTextBox 
                                    ID="SearchBoxModule" 
                                    AutoPostBack="true" 
                                    OnCallback="Page.loadSearchHeader"  
                                    OnTextChanged="Page.loadSearchHeader" 
                                    OnInit="Page.setSearchHeaderText" 
                                />
                            </div>
	                    </prop:Headertemplate>
					</com:TTemplateColumn>
					

If you click on the link of the linkbutton, nothing happens ....
With 3.2.4 and php 5.6 this has worked fine.

Thanks and best regards
Jürgen

**Comment by ctrlaltca** [comment]
Sorting seems to work in both `TDataGrid` and `TActiveDataGrid`:
http://pradoframework.net/demos/quickstart/?page=Controls.Samples.TDataGrid.Sample4
http://pradoframework.net/demos/quickstart/?page=ActiveControls.Samples.TActiveDataGrid.Sample4
The last column "Rating" is a `TTemplateColumn`/`TActiveTemplateColumn`.
Even if i replace the `TActiveTemplateColumn` with a `TTemplateColumn` in the `TActiveDataGrid` sample, it still works (but requires a postback).
I suggest you to actually look at the server response/logs to see what's going on.

**Comment by ctrlaltca** [comment]
Did you manage to fix your problem?

**Comment by jo49bimpf** [comment]
yess, sorry for the delay. I was out for holidays.
I fixed it, it was a interferrence with topic #680 
The toggle-buttion was aadded class from my pre-developer.
After finding and fixing this, the TactiveDatagrid was working fine again.
