### ISSUE TITLE
TRequiredFieldValidator doesn't work with TActiveListBox

### ISSUE THREAD

**Issue by ganiuszka** [pradosoft/prado#683]
Hello The Prado Group,

I noticed that TRequiredFieldValidator doesn't work with TActiveListBox because although selecting items on TActiveListBox the validator still requires selecting an item.

After looking at the validation script I prepared a patch that fixes this problem. I think that this is a problem with using validators for active list-type controls. In this case they are: TActiveCheckBoxList, TActiveRadioButtonList and TActiveListBox.

I tested the patch for TActiveListBox. I use PRADO 4.0.1.

Thank you in advance for considering this change.

Best regards.
Marcin Haba (gani)

[prado_fix_trequired_field_validator_with_tlistbox.patch.txt](https://github.com/pradosoft/prado/files/2260250/prado_fix_trequired_field_validator_with_tlistbox.patch.txt)

**Comment by ctrlaltca** [comment]
Hi! your patch looks reasonable, will review and test it in the next few days. Thank you!

**Comment by ctrlaltca** [comment]
It looks like we had a way to avoid specifying all the subclasses of normal controls in validators, but it broke during the namespace update.
This has been rectified in #684, can you give it a test please?

**Comment by ganiuszka** [comment]
Hello The PRADO Group,

I have fetched this pull request and I tested it with my application. It works very well and the problem stopped apearing.

Thank you for your help with fixing it.

Best regards
Marcin Haba (gani)

**Comment by ctrlaltca** [comment]
Thank you for your feedback, I'll wait a few days if @LCSKJ or anyone else want to comment on it, then if no problem arise I'll merge it.
I hope to get a few more changes ready and to release 4.0.2 soon.
