### ISSUE TITLE
TActiveRepeater sample, Repeater2 not rendered

### ISSUE THREAD

**Issue by drigolin** [pradosoft/prado#685]
Looking at samples I have discovered that TActiveRepeater sample in Quickstart tutorial the Repeater2 component isn't rendered with his ID. In that way when you press "Save" results aren't displayed.
In response Prado send the content of the div but, without the ID, the content cannot be updated.

**Comment by ctrlaltca** [comment]
Nice catch! The problem seems due to the fact that `Repeater2` is nested inside a `<com:TSafeHtml />` control.
`

**Comment by ctrlaltca** [comment]
Fixed in https://github.com/pradosoft/prado-demos/commit/79300c8f84c8d7bc3da9ac718758844a96c55668, thank you!
