### ISSUE TITLE
Dynamic components not available via ID by magic method

### ISSUE THREAD

**Issue by drigolin** [pradosoft/prado#693]
When we create into onInit a new dynamic component assigning it an ID and adding the new component to parent component Controls Collection the control cannot be referenced into the code using the $this->IDOfMyDynamicControl but the component can be found using a $this->findControl("IDOfMyDynamicControl").
Looking at framework implementation it seems that the magic method in charge of finding controls use a lookup array (_rf[8])  where are present only components IDs coming from a template.
Maybe we have to use another method to add our dynamic created components?
It will be nice to have dynamic component behaves as any other component.

**Comment by drigolin** [comment]
Sorry looking better at TControl I saw the registerObject() that does what I need. 

Well done!

**Comment by ctrlaltca** [comment]
Yep, those are 2 separated commands because not every control is a NamingContainer.
```php
$button = new MyControl;
$button->setID('IDMyControl');
$this->getControls()->add($button);
$this->registerObject('IDMyControl', $button);
```
