### ISSUE TITLE
Undefined variable: conn notice in Active Record Scaffold

### ISSUE THREAD

**Issue by ganiuszka** [pradosoft/prado#694]
Hello PRADO Group,

Today first time I tried Active Record Scaffold controls in PRADO. It is very nice feature and thank you for it.

One minor notice is that when I use:

<com:TScaffoldView RecordClass="UserRecord" />

and I want to click 'Add new record' button then I receive:

Prado\Exceptions\TPhpErrorException

[Notice] Undefined variable: conn (@line 38 in file /var/www/zbor/protected/vendor/pradosoft/prado/framework/Data/ActiveRecord/Scaffold/InputBuilder/TScaffoldInputBase.php).

The $conn variable is missing and it seems that this variable isn't used here. Even when it would be used, then there isn't any constructor that could get this $conn value.

I prepared a patch that I would like to propose you. I have to admit that I tested it only with MySQL. I prepared it for PRADO version 4.0.2.

[fix_scaffold_input_builder_base.patch.txt](https://github.com/pradosoft/prado/files/3204293/fix_scaffold_input_builder_base.patch.txt)

Thank you in advance for your consideration about this patch. If you need any more information from me, please don't hesitate to ask.

Best regards.
Marcin Haba (gani)

**Comment by ctrlaltca** [comment]
Hi, your patch looks fine, I've just merged it, thank you!
