### ISSUE TITLE
Alternative for some php functions used in Prado Framework.

### ISSUE THREAD

**Issue by maheshnironi2016** [pradosoft/prado#695]
Hello,

Please guide, What will be the alternative for below php functions which are used in Prado Framework.
exec(),eval(),shell_exec(),passthru()

Thank you.

**Comment by ctrlaltca** [comment]
I'm not aware of any usage of `exec(), shell_exec(), passthru()` in the code of Prado.
There are still some usage of `eval()`, that will eventually be replaced in the future with alternatives.

**Comment by maheshnironi2016** [comment]
Thanks for quick reply,

When we install Prado through composer then in vendor folder we have some packages with all 3 functions exec(), shell_exec(), passthru() used in it. So If execution of these functions stopped globally then it will affect in framework flow or not?

All are default packages so I am not sure where it will affect in framework and because of that what problems I will face in my application.

Thank you.

**Comment by ctrlaltca** [comment]
`passthru()` is only used by maintenance scripts (version update/package creation/etc..) in the `ezyang/htmlpurifier` package. You don't need to run them when using the package.
`shell_exec()` is used by maintenance scripts in the `ezyang/htmlpurifier` and nikic/php-parser packages and by dependencies of the prado CLI: `sebastian/environment`, `symfony/console`.
`exec()` is used in tests for some packages (`herrera-io/phar-update`, `phpunit/phpunit-selenium`, `pradosoft/apigen`, `symfony/console`, `tracy/tracy`) and in dependencies of the prado CLI (`symfony/console`, `psy/psysh`) .
So, only prado CLI is directly affected by limitations in availability of these methods.
