### ISSUE TITLE
Handling onclick from inside a TActiveRepeater

### ISSUE THREAD

**Issue by drigolin** [pradosoft/prado#701]
I would like to handle a button click event from a TActiveButton inside a TActiveRepeater in a custom TTemplateComponent. ButtonClick handler is defined into TTemplateComponent class.

<com:TActiveRepeater >
<prop:HeaderTemplate>
 <com:TActiveButton OnClick="handlerOnTemplateComponent" />
...
But this handler cannot be "found". I have tried using many Parent nesting level but it seems that HeaderTemplate doesn't have a parent defined yet.

Any suggestion?

**Comment by ctrlaltca** [comment]
I'd try `Page.handlerOnTemplateComponent` or `SourceTemplateControl.handlerOnTemplateComponent`

**Comment by drigolin** [comment]
Thank you!!!! It works. What's the difference between SourceTemplateControl and TemplateControl properties in the context of a TemplateControl?

**Comment by ctrlaltca** [comment]
`TemplateControl` returns the control whose template contains the button. In your case, it returns the `HeaderTemplate` of the `TActiveRepeater`.
`SourceTemplateControl` also looks for a TemplateControl, but it goes up in the controls hierarchy until it finds the TemplateControl that hash been directly loaded from a class/template file.

**Comment by drigolin** [comment]
Great! Well to known. I didn't find samples using that naming syntax.
