### ISSUE TITLE
index.php?TWsatLogin redirecting to protected/Pages/TWsatLogin.php

### ISSUE THREAD

**Issue by opendast** [pradosoft/prado#704]
Hello, as for ticket 660,
now in Prado 4.1 - php 7.2 there is the same error. 
`component type 'TWsatLogin'. This may be caused by the following parsing error in the TWsatLogin class file: [Warning] include_once(/var/www/html/[FOLDER]/protected/Pages/TWsatLogin.php): failed to open stream: No such file or directory (@line 393 in file /var/www/html/[FOLDER]/protected/vendor/pradosoft/prado/framework/PradoBase.php).`

**Comment by ctrlaltca** [comment]
Hi, can you please explain your problem furthermore?
The `index.php?TWsatLogin` url in the issue title is not correct, it's missing the "wsat" sevice name; it should looks like this:
```
http://localhost/yoursite/index.php?wsat=TWsatLogin
```
Since the "TWsatLogin" url is not requested on the `wsat` service, the `page` service is trying to serve the request instead.

**Comment by opendast** [comment]
URL 
`http://192.168.200.92/carte-prado/index.php?wsat=TWsatLogin`
error thrown:
`Prado\Exceptions\TInvalidOperationException
Description

Unknown component type 'TWsatLogin'. This may be caused by the following parsing error in the TWsatLogin class file: [Warning] include_once(/var/www/html/carte-prado/protected/Pages/TWsatLogin.php): failed to open stream: No such file or directory (@line 393 in file /var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/PradoBase.php).
Source File

/var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/PradoBase.php (400)

0389:                 if(!$checkClassExistence || (!class_exists($className,false) && !interface_exists($className, false)))
0390:                 {
0391:                     try
0392:                     {
0393:                         include_once($path);
0394:                         if(class_exists($namespace, false) || interface_exists($namespace, false))
0395:                             class_alias($namespace, $className);
0396:                     }
0397:                     catch(\Exception $e)
0398:                     {
0399:                         if($checkClassExistence && !class_exists($className,false))
0400:                             throw new TInvalidOperationException('prado_component_unknown',$className,$e->getMessage());
0401:                         else
0402:                             throw $e;
0403:                     }
0404:                 }
0405:             }
0406:         }
0407:     }
0408: 
0409:     /**
0410:      * Translates a namespace into a file path.
0411:      * The first segment of the namespace is considered as a path alias
0412:      * which is replaced with the actual path. The rest segments are

Stack Trace

#0 /var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/PradoBase.php(148): Prado\PradoBase::using('Application\\Pag...')
#1 [internal function]: Prado\PradoBase::autoload('Application\\Pag...')
#2 [internal function]: spl_autoload_call('Application\\Pag...')
#3 /var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/Web/Services/TPageService.php(513): is_subclass_of('Application\\Pag...', '\\Prado\\Web\\UI\\T...')
#4 /var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/Web/Services/TPageService.php(474): Prado\Web\Services\TPageService->createPage('TWsatLogin')
#5 /var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/TApplication.php(1202): Prado\Web\Services\TPageService->run()
#6 /var/www/html/carte-prado/protected/vendor/pradosoft/prado/framework/TApplication.php(391): Prado\TApplication->runService()
#7 /var/www/html/carte-prado/index.php(24): Prado\TApplication->run()
#8 {main}

2020-01-27 11:46 Apache/2.4.29 (Ubuntu) PRADO/4.0.0 `

**Comment by ctrlaltca** [comment]
From the error it looks like you are running PRADO/4.0.0. Can you try to update to the latest version?
Also, did you add the relevant lines to application.xml to enale wsat?

**Comment by opendast** [comment]
I'll upgrade to 4.1 and try
added:
`<service id="wsat" class="Prado.Wsat.TWsatService" Password="password" />`
line to application.xml

**Comment by ctrlaltca** [comment]
Did you solve your problem by updating to 4.1?

**Comment by sicutdeux** [comment]
This is fixed updating to 4.1.1
