### ISSUE TITLE
empty function with prado not working properly for PHP7.2

### ISSUE THREAD

**Issue by pinal-r** [pradosoft/prado#705]
empty(($this->currencylst->SelectedValue))

Above code lstCurrency is active drop down and I am checking whether selected value is empty or not its working fine for previous php version but for PHP7.2 it returns opposite result return empty true though string is not empty. Does prado has overridden empty funtion or what is the excact problem by which this is happening. ?

**Comment by ctrlaltca** [comment]
I'm not aware of any change in php 7.2 `empty()`'s behavior.
Can you try to dump `$this->currencylst->SelectedValue` to a variable and `var_export()` it to see its actual content?
About Prado, there has been a quite recent change on how list controls behave when an empty PromptValue is set on them. Please have a look if https://github.com/pradosoft/prado/pull/684 can be the cause of your problems.
