### ISSUE TITLE
Feature request: Add support for PostgreSQL 12

### ISSUE THREAD

**Issue by ganiuszka** [pradosoft/prado#708]
Hello the PRADO Group,

I would like to ask about adding in the PRADO framework support for PostgreSQL 12.

If the PRADO framework is used with PostgreSQL 12 then occurs a SQL error:

Undefined column: 7 ERROR:  column "consrc" does not exist

In TPgsqlMetaData module are getting data from two SQL columns that are no longer used in PostgreSQL 12. They are:

 - pg_constraint.consrc
 - pg_attrdef.adsrc

According to https://www.postgresql.org/docs/12/release-12.html there is recommendation to replace them by:

 - for consrc: pg_get_constraintdef() or pg_get_expr(conbin, conrelid)
 - for adsrc: pg_get_expr(adbin, adrelid).

pg_get_expr() exists in PostgreSQL from version 7.4, and pg_get_constraintdef() from version 7.3.

I prepared a proposed patch that adds this support for PostgreSQL 12. I did basic tests with PostgreSQL versions: 9.2.24, 11.7 and 12.2.

If you would like to add this patch, I can prepare pull request with it.

[prado-add-postgresql-12-support.patch.txt](https://github.com/pradosoft/prado/files/4301327/prado-add-postgresql-12-support.patch.txt)

Thanks in advance for considering this patch.

Best regards,
Marcin Haba (gani)

**Comment by ctrlaltca** [comment]
Go on with the PR, and thank you for the patch!
The change related to `adsrc` looks fine;
In the change that removes the usage of `consrc`, `pg_get_constraintdef` was already being used for `contype=f` (foreign keys), can you please check if it's fine using it also for other constraints types?
They are:
 * c = check constraint,
 * p = primary key constraint
 * u = unique constraint
 * t = constraint trigger
 * x = exclusion constraint

Thank you

**Comment by ganiuszka** [comment]
Hello ctrlaltca,

Thanks for your quick response.

Yes, of course. I have checked it for all constraint types on PostgreSQL versions 9.2.24, 11.7 and 12.2. 

In the PRADO framework from `pg_constraint` table are taken only 'foreign key' and 'check' contraints (using is only 'foreign key' constraint so far). For these two the patch with `pg_get_constraintdef(oid)` will work fine and compatible with current behavior, as you can see in files with test results. For the rest `consrc` values are empty.

The interesting thing is that `consrc` (and also `pg_get_expr(conbin, conrelid)`) values are empty for 'foreign key' constraint. Only `pg_get_constraintdef(oid)` shows expected by the PRADO framework results for them. Using `pg_get_constraintdef(oid)` to get `consrc` is also recommended at the official PostgreSQL documentation:

"_`consrc` is not updated when referenced objects change; for example, it won't track renaming of columns. Rather than relying on this field, it's best to use `pg_get_constraintdef()` to extract the definition of a check constraint._"

source: https://www.postgresql.org/docs/11/catalog-pg-constraint.html

Here are test tables and test results:

[constraints_test.sql.txt](https://github.com/pradosoft/prado/files/4301891/constraints_test.sql.txt)
[postgresql-9.2.24-constraint-test.out.txt](https://github.com/pradosoft/prado/files/4301892/postgresql-9.2.24-constraint-test.out.txt)
[postgresql-11.7-constraint-test.out.txt](https://github.com/pradosoft/prado/files/4301893/postgresql-11.7-constraint-test.out.txt)
[postgresql-12.2-constraint-test.out.txt](https://github.com/pradosoft/prado/files/4301894/postgresql-12.2-constraint-test.out.txt)

Thank you in advance for reviewing the test results and for your opinion about it.

Best regards,
Marcin Haba (gani)

**Comment by ctrlaltca** [comment]
Thank you for the time spent testing your change, everything looks fine.
Do you want to open a PR so you get proper credits for your change?

**Comment by ganiuszka** [comment]
Hello ctrlaltca,

Great, thank you.

I have just prepared new pull request #709 with this change.

Thank you in advance for applying this change.

Best regards,
Marcin Haba (gani)
