### ISSUE TITLE
THtmlArea not loading properly in FireFox

### ISSUE THREAD

**Issue by jmartens** [pradosoft/prado#716]
I was just infiormed by a user that in one of our applications the THtmlArea does not render properly in FireFox 70.0.1 (64-bits):

The console lists the following:
```Het script van ‘https://dgrt/assets/8c13dd76/tiny_mce/langs/nl.js’ is geladen, hoewel het MIME-type ervan (‘text/html’) geen geldig JavaScript-MIME-type is.
dgrt
Laden voor het <script> met bron ‘https://dgrt/assets/8c13dd76/tiny_mce/langs/nl.js’ is mislukt. dgrt:1:1
Failed to load: https://dgrt/assets/8c13dd76/tiny_mce/langs/nl.js tiny_mce.js:1:123978
Het script van ‘https://dgrt/assets/8c13dd76/tiny_mce/themes/advanced/langs/nl.js’ is geladen, hoewel het MIME-type ervan (‘text/html’) geen geldig JavaScript-MIME-type is.
dgrt
Laden voor het <script> met bron ‘https://dgrt/assets/8c13dd76/tiny_mce/themes/advanced/langs/nl.js’ is mislukt. dgrt:1:1
Failed to load: https://dgrt/assets/8c13dd76/tiny_mce/themes/advanced/langs/nl.js tiny_mce.js:1:123978
```

**Comment by jmartens** [comment]
Might not be related to FF only as the file referred to seems not present, it might be triggered as the Browser language and interface is dutch (nl):

![image](https://user-images.githubusercontent.com/593327/84264193-0ab31380-ab21-11ea-85eb-e15915e1cd7d.png)

How do I force proper publication of the dutch assets as well?

**Comment by jmartens** [comment]
It works for THtmlArea with the new version.

**Comment by ctrlaltca** [comment]
Thank you for the feedback
