### ISSUE TITLE
HTMLArea causing internal server errors on editItem() (comparable to THtmlArea in #710?)

### ISSUE THREAD

**Issue by jmartens** [pradosoft/prado#718]
It seems THtmlArea4 is suffering from the same issue as THtmlArea as described in #710 after an exception there is an uncaught TypeError similar as found in #710 for THtmlArea:

```
ajax3.js:71 Prado\Exceptions\TInvalidOperationException with message "Component property 'Prado\Security\TUser.cn' is not defined." in ${PradoFramework}\TComponent.php(652)
ajax3.js:72 Stack trace:
ajax3.js:80 #0 ${DocumentRoot}protected\pages\Dashboard.php(74)
ajax3.js:90 Uncaught TypeError: Cannot read property 'join' of undefined
    at Object.logFormatException (ajax3.js:90)
    at klass.errorHandler (ajax3.js:419)
    at fire (jquery.js:3291)
    at Object.fireWith [as rejectWith] (jquery.js:3421)
    at done (jquery.js:9535)
    at XMLHttpRequest.<anonymous> (jquery.js:9785)
```

**Comment by ctrlaltca** [comment]
When an exception occurs, prado uses [Exception::getTrace](https://www.php.net/manual/en/exception.gettrace.php) to get the exception trace, that is supposed to contain an array of method arguments in the "args" element.
In your case it seems that this element is not available.
The only possible cause for this that I've been able to find is a new php.ini parameter called `zend.exception_ignore_args` that has been added in php 7.4.
I'll add a check to avoid the error, can you please confirm if you have this parameter enabled in your php.ini?
