### ISSUE TITLE
New app created gives error "Unable to find prado framework path"

### ISSUE THREAD

**Issue by ashvinih** [pradosoft/prado#721]
Steps:
Installed Prado on a WSL Ubuntu php dev environment using composer

created a prado project using prado-cli.php

Getting error message on opening project home page in browser

error message: Unable to find prado framework path /var/www/html/prado1/protected/vendor/pradosoft/prado/framework/prado.php

Observation:
I noticed the file "prado.php" located in "/var/www/html/prado1/protected/vendor/pradosoft/prado/framework/" directory is named with a capital "Prado.php"

**Comment by ctrlaltca** [comment]
I'm sorry, prado-cli is really out of date and neews some serious reworking, if not a complete rewrite.
In order to creat a new project i can suggest you to us this: https://github.com/pradosoft/prado-app

**Comment by ctrlaltca** [comment]
I decided to remove the create-project function altogether from prado-cli.
It just doesn't fit in the flow of installing an application using composer.
