### ISSUE TITLE
Problem with TactiveButton Text  property 

### ISSUE THREAD

**Issue by Robcrack** [pradosoft/prado#722]
Problem with TactiveButton Text, the value of the text property is not updated and only the value property is updated
Html example:

`<button type="submit" name="ctl0$btnbuscar" id="ctl0_btnbuscar" class="site-btn" value="Realizado..."  disabled="disabled">Buscar</button>`

**Comment by ctrlaltca** [comment]
Hello, thank you for reporting your issue.
A fix has been applied in b6c26cc.
Can you please test it and report back if it works for you?

**Comment by Robcrack** [comment]
Works Perfect, thank you very much

**Comment by Robcrack** [comment]
It worked fine, thank you very much
