### ISSUE TITLE
Extract the sqlmap as a standalone library 

### ISSUE THREAD

**Issue by videni** [pradosoft/prado#723]
I'd like to use the SQLMap feature with doctrine, Can we extract the SQLMap as a standalone lib?, so that we can use it out of this framework.

**Comment by ctrlaltca** [comment]
Of course you can. The SQLMap license is https://github.com/pradosoft/prado/blob/master/LICENSE, copyright goes to the original author Wei Zhuo <weizhuo[at]gmail[dot]com>

**Comment by ctrlaltca** [comment]
No fix needed, closing.
