### ISSUE TITLE
Ajax queue improvement

### ISSUE THREAD

**Issue by ganiuszka** [pradosoft/prado#724]
Hello The Prado Group,

I experienced a problem in Prado with callback requests that are send one after the other. I mean situation where I have two active controls (two TActiveLinkButton for example), let's call them A and B, I click on A and after that I click on the B. In this time is sent one request for A, the second request for B is waiting in an ajax queue. Once the response on the first request comes back, then is sent request for B. If on A request the page state is modified on the server side (e.g. by setting a view state), then the B request usually sends to the server side with outdated page state. It is because request data is added to queue at moment of clicking at A and B. not at the moment of real sending request. If the request A will take 3 second, then during this time can be added to ajax queue many other requests that will be sent with data that is out-of-date.

In attachment I added a patch. I would like to propose it as a solution for this problem. If you find it useful, I can prepare a pull request.

Thank you in advance for considering this patch.

Best regards,
Marcin Haba (gani)

[improve-ajax-queue.patch.txt](https://github.com/pradosoft/prado/files/5484912/improve-ajax-queue.patch.txt)

**Comment by ctrlaltca** [comment]
Your proposed change seems really beneficial to avoid problems on applications, expecially when the backend is slow to respond to ajax requests.
I've created a pull reuqest with your patch and a testcase in #725, please have a look if it's ok for you.

**Comment by ganiuszka** [comment]
Hello ctrlaltca,

Thank you for your positive feedback about the patch.

I have looked at the pull request. Yes, it is OK for me.

Thank you.

Best regards,
Marcin Haba (gani)

**Comment by ctrlaltca** [comment]
Well then, I'll wait for CI to finish and then merge.
Thank you for the patch!
