### ISSUE TITLE
THttpRequest constructUrl SID Throws Fatal Errors (String Size Overflow or Allowed Memory Size Exhausted)

### ISSUE THREAD

**Issue by jkmbooth** [pradosoft/prado#726]
The following line within the constructUrl method is randomly throwing two Fatal Errors:

`if(defined('SID') && SID != '' && !$this->_cookieOnly)`

This appears to be intermittent - the exact user actions do not always throw an error, but when an error does occur it shows one of the following:

-  **Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 1109415573 bytes)** - Using memory_get_usage directly before this line of code returns only 13329624 bytes.

- **Fatal error: String size overflow**

**Comment by ctrlaltca** [comment]
SID is a php-defined constant containind the php session ID (if any) in a url parameter style, like `name=ID`.
It sounds strange it could need so much ram to overflow the memory limit.
To be honest I always set THttpSession's CookieMode to "Only" in application.xml, that is the same as enabling php's [session.use-only-cookies](https://www.php.net/manual/en/session.configuration.php#ini.session.use-only-cookies), that is also the default since php 5.3:
```
<module id="session" SessionName="xxx" CookieMode="Only" UseCustomStorage="true" AutoStart="true" TimeOut="3600" Cookie.HttpOnly="true" Cookie.SameSite="Lax"/>
```
Can I ask you some informations on your environment: php version and how the THttpSession module is configured?
Also, can you try to var_export(SID) to see if it actually contains anything?
Thank you

**Comment by jkmbooth** [comment]
I'm using PHP 5.4.45 with the 3.2.2 Framework - appreciate this is unsupported but I cannot see any amendments to that particular method in the latest stable release.

I'm outputting a table that contains hyperlinks (20 records/rows) - each row I'm calling:

`$this->Service->constructUrl('assets.ListAssets', $get_parameters);`

For the rows that are processed var_export(SID) is empty, but then randomly get one of the error messages.

**Comment by ctrlaltca** [comment]
> For the rows that are processed var_export(SID) is empty, but then randomly get one of the error messages before var_export(SID) can output.

This suggest me that the culprit could be the row just before the var_export, that is the one calling `$this->getUrlManagerModule()->constructUrl(...)`. That method loops over all the parameters, urlencodes them if necessary, concatenates them and returns the full url; this could also explain the "string size overflow".

Can you please try to set `$get_parameters = array();` just before the call to `$this->Service->constructUrl('assets.ListAssets', $get_parameters);` in your code and see if the problem stil occurs?
If it doesn't, we can try to understand what value inside `$get_parameters` is causing the problem.
If it doesn't, I'm not sure how to proceed right now.

**Comment by jkmbooth** [comment]
The `$this->getUrlManagerModule()->constructUrl(...)` call returns and following that call I'm able to output the memory_get_usage () value (13329624 bytes) - so it appears to be returning fine from that call.

I have however tried setting `$get_parameters = array();` just before the `$this->Service->constructUrl('assets.ListAssets', $get_parameters);` call.

The error only occurs after a postback request, I don't know if that has any relevance? However it randomly fails still - some postback requests will be fine although the user action is exactly the same.

**Comment by ctrlaltca** [comment]
I'm not sure how to debug this. Maybe you can share a small example where the problem occurs, or try to run the same application in another environment to see if the problem only occurs in that specific version of php?

**Comment by ctrlaltca** [comment]
Also, can you try to remove the offending part of code:
```php
		if (defined('SID') && SID != '' && !$this->_cookieOnly) {
			return $url . (strpos($url, '?') === false ? '?' : ($encodeAmpersand ? '&amp;' : '&')) . SID;
		} else {
			return $url;
		}
```
and replace it with just:
```
		return $url;
```
And see if it fixes the problem?

**Comment by jkmbooth** [comment]
Amending the constructUrl method to just `return $url;` works, I don't get any memory exhausted or overflow errors.

I will amend the method back and then test another PHP version as I'd like to try and understand the issue - it's strange that the errors only occur on postback. I will also look at providing you with a sample. This is likely to be next week.

**Comment by jkmbooth** [comment]
Hi, I moved the application to another server and the issue went away - I
never got to the root cause of the issue so I put it down as a server
configuration issue.

**Comment by ctrlaltca** [comment]
Thank you for the feedback. I'm closing this issue them.
