### ISSUE TITLE
[Warning] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by PixelHomie** [pradosoft/prado#727]
https://github.com/pradosoft/prado/blob/a8469e327b6d3d1796022618fb667ae8bd65de00/framework/Data/Common/Mysql/TMysqlMetaData.php#L274

If the TDbCommand failed to execute the query SQL (e.g Base table or view not found) $result will be false which leads to the following warning:
`Prado\Exceptions\TPhpErrorException: [Warning] count(): Parameter must be an array or an object that implements Countable`

It should be changed to 
```
try {
  $result = $command->queryRow();
  return $result && count($result) > 0 && $result['Table_type'] === 'VIEW';
} catch (TDbException $e) {
  $table = $schemaName === null ? $tableName : $schemaName . '.' . $tableName;
  throw new TDbException('dbcommon_invalid_table_name', $table, $e->getMessage());
}
```

**Comment by ctrlaltca** [comment]
Fixed in master, thank you!
