### ISSUE TITLE
repository description issue?  still labelled as php 5 (&7), should be 7 only, yes?

### ISSUE THREAD

**Issue by javalizard** [pradosoft/prado#729]
Given the leaps in speed of PHP 7, PRADO has decided to go php 7 only if i have seen and remember correctly.  yes?  shouldn't that be reflected in the description of the project?

**Comment by ctrlaltca** [comment]
Prado 4.0 is still supported, an it includes support for php 5.
But i guees you are right, the project descripton can be changed.

**Comment by javalizard** [comment]
that should be made a little more clear, maybe in the READ ME for github?  i do like the backward compatibility statement it makes, though it is so highly recommended to be php 7.
