### ISSUE TITLE
Prado on Centos 8 help

### ISSUE THREAD

**Issue by xSigdsx** [pradosoft/prado#731]
Hi,

the reason why I'm working in Prado is for my thesis degree.  . I developed the app in Windows 10, but I needed to release the project in a server with Linux CentOS 8. The app work fine on Windows 10, but on Centos 8, it gave me this error:

_Invalid template syntax: Unknown component type 'LoginPortlet'. This may be caused by the following parsing error in the LoginPortlet class file: [Warning] include_once(LoginPortlet.php): failed to open stream: No such file or directory (@line 291 in file /var/www/html/sigds/prado/framework/PradoBase.php)._

Please if anyone know why happen this! Every file is where its suppost to be, it never happen this error on windows 10, but on centos 8 its drive me crazy with this.

**Comment by LCSKJ** [comment]
I know this sounds stupid, but first thing that comes to my mind is that Linux is case-sensitive and Windows is not. The autoloader looks for a file named just like the class name and may not find it if case is different.

**Comment by xSigdsx** [comment]
> I know this sounds stupid, but first thing that comes to my mind is that Linux is case-sensitive and Windows is not. The autoloader looks for a file named just like the class name and may not find it if case is different.

someone told me before about the case-sensitive issue, i have changed the name LoginPorlet, to loginporlet in some php files, but that exact error happen still.  So the classname of LoginPorlet, maybe is the same but without capital letter? 

i have the LoginPorlet.php and LoginPorlet.tpl, the problem happens in the file Home.page, its said the same "LoginPorlet" in line 2, reffering the php file that its call the same

_Source File

/var/www/html/sigds/Geoportal/protected/pages/Home/Home.page (2)

0001: ﻿<com:TContent ID="sidebar">
0002:     <com:LoginPortlet Visible="<%= $this->User->IsGuest %>" />
0003:     <com:SideBarMenu ID="sidebarmenu" Visible="<%= !$this->User->IsGuest %>" />
0004: </com:TContent>
0005: <com:TContent ID="content">
0006:     <div class="art-post-inner art-article">
0007:         
0008:     </div> 
0009: </com:TContent>_



thanks for comment this post!

**Comment by ctrlaltca** [comment]
To avoid problems on case-sentitive file systems, ensure you choose a file name style and stick to it.
Usually in Prado (and more generically in php) class names are in StudlyCaps (as per the PSR standard: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md), so to avoid problems when using external libraries you may want to stick to the "LoginPortlet" name.
So first make sure the file names are exactly LoginPortlet.php/.tpl and that you are using that exact name in every place where that class is referenced in the code.
If you still get the "Unknown component type" error, probably php doesn't know the path where it should look to find that file.
You can add to your `application.xml` configuration a directive to fix this:
```
<application id="xxx" mode="Debug">
  <paths>
    <using namespace="Application.Common.*" />
    <using namespace="Application.Pages.Whatever.*" />
  </paths>
```
"Application" refers to the base path of the application, i.e. the "protected" folder. So eg. `Application.Pages.Whatever.*` will include every file in the `protected/Pages/Whatever/` folder. You may want to change this to the actual path of your LoginPortlet.php file.
Here's the relevant documentation: http://www.pradoframework.net/demos/quickstart/?page=Configurations.AppConfig

**Comment by xSigdsx** [comment]
> To avoid problems on case-sentitive file systems, ensure you choose a file name style and stick to it.
> Usually in Prado (and more generically in php) class names are in StudlyCaps (as per the PSR standard: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md), so to avoid problems when using external libraries you may want to stick to the "LoginPortlet" name.
> So first make sure the file names are exactly LoginPortlet.php/.tpl and that you are using that exact name in every place where that class is referenced in the code.
> If you still get the "Unknown component type" error, probably php doesn't know the path where it should look to find that file.
> You can add to your `application.xml` configuration a directive to fix this:
> 
> ```
> <application id="xxx" mode="Debug">
>   <paths>
>     <using namespace="Application.Common.*" />
>     <using namespace="Application.Pages.Whatever.*" />
>   </paths>
> ```
> 
> "Application" refers to the base path of the application, i.e. the "protected" folder. So eg. `Application.Pages.Whatever.*` will include every file in the `protected/Pages/Whatever/` folder. You may want to change this to the actual path of your LoginPortlet.php file.
> Here's the relevant documentation: http://www.pradoframework.net/demos/quickstart/?page=Configurations.AppConfig



> To avoid problems on case-sentitive file systems, ensure you choose a file name style and stick to it.
> Usually in Prado (and more generically in php) class names are in StudlyCaps (as per the PSR standard: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md), so to avoid problems when using external libraries you may want to stick to the "LoginPortlet" name.
> So first make sure the file names are exactly LoginPortlet.php/.tpl and that you are using that exact name in every place where that class is referenced in the code.
> If you still get the "Unknown component type" error, probably php doesn't know the path where it should look to find that file.
> You can add to your `application.xml` configuration a directive to fix this:
> 
> ```
> <application id="xxx" mode="Debug">
>   <paths>
>     <using namespace="Application.Common.*" />
>     <using namespace="Application.Pages.Whatever.*" />
>   </paths>
> ```
> 
> "Application" refers to the base path of the application, i.e. the "protected" folder. So eg. `Application.Pages.Whatever.*` will include every file in the `protected/Pages/Whatever/` folder. You may want to change this to the actual path of your LoginPortlet.php file.
> Here's the relevant documentation: http://www.pradoframework.net/demos/quickstart/?page=Configurations.AppConfig

Thank u so much for your help, in fact, i have 3 folders on my prado system. It is : Geoportal, personal and prado. The error i wrote, it happen for a capital letter on my folder "common" - "Common" on "Geoportal", so i changed in the applicaction.xml and the error dissapear! I am so glad, now it gave me a connection error with the postgres user, but, if i run on apache, the "personal" folder, it gave me an identic error as the one before, it said:
_Unknown component type 'master'. This may be caused by the following parsing error in the master class file: [Warning] include_once(${DocumentRoot}/sigds/personal/protected/pages/master.php): failed to open stream: No such file or directory (@line 316 in file ${DocumentRoot}/sigds/prado/framework/PradoBase.php)._

It is almoust the same error than before! so i went to the application.xml in the "personal" folder and change de capital letter to the folder "Pages" where is my master.php, that would be the solution i thought, but this time, it did not worked,

![image](https://user-images.githubusercontent.com/79811369/109561876-ba635380-7aab-11eb-9180-999ac4e38616.png)

As you can see in the picture, now i have all the same, with the same names, but in the error in firefox say this

[Warning] include_once(${DocumentRoot}/sigds/personal/protected/**pages**/master.php):

the "pages" it did not upgrade with the edition in application.xml, because its still without the capital letter, is has to be "Pages" like i have on my folder and my application.xml on the folder personal/protected.  I think the connection issue with postgres it is maybe because the master.php its not getting call by prado, please if you know what could be.. i am here everyday workin on this! How could i change that path? i did it in the application.xml , but i did not work :c 
Thanks for the comment!

**Comment by xSigdsx** [comment]
> To avoid problems on case-sentitive file systems, ensure you choose a file name style and stick to it.
> Usually in Prado (and more generically in php) class names are in StudlyCaps (as per the PSR standard: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md), so to avoid problems when using external libraries you may want to stick to the "LoginPortlet" name.
> So first make sure the file names are exactly LoginPortlet.php/.tpl and that you are using that exact name in every place where that class is referenced in the code.
> If you still get the "Unknown component type" error, probably php doesn't know the path where it should look to find that file.
> You can add to your `application.xml` configuration a directive to fix this:
> 
> ```
> <application id="xxx" mode="Debug">
>   <paths>
>     <using namespace="Application.Common.*" />
>     <using namespace="Application.Pages.Whatever.*" />
>   </paths>
> ```
> 
> "Application" refers to the base path of the application, i.e. the "protected" folder. So eg. `Application.Pages.Whatever.*` will include every file in the `protected/Pages/Whatever/` folder. You may want to change this to the actual path of your LoginPortlet.php file.
> Here's the relevant documentation: http://www.pradoframework.net/demos/quickstart/?page=Configurations.AppConfig

Sorry for the long comment before, now i dont have any problem of **_Unknown component type 'master'_** it gave me now a problem of connection to my postgres db, i will try to fix it, if i made it, i will finally end my thesis
