### ISSUE TITLE
General Inability of Modules to access page events.  No event between creation of page and running of page

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#735]
If a module wants to handle a page event, there is no general event/method/location where a module can access a page events before the page events are run.  This is a severe bug as it limits functionality of all modules to be able to patch into page events.

Solution: In TPageService add a new event onPreRunPage that is executed in runPage between the Properties being set and the page being run.

`
	/**
	 * Executes a page.
	 * @param TPage $page the page instance to be run
	 * @param array $properties list of initial page properties
	 */
	protected function runPage($page, $properties)
	{
		foreach ($properties as $name => $value) {
			$page->setSubProperty($name, $value);
		}
		$this->onPreRunPage($page);
		$page->run($this->getResponse()->createHtmlWriter());
	}
	
	/**
	 * This is run just before the page is run.  Any part of the system can now patch into the page.
	 *	@param mixed what is passed as the parameter to the event
	 */
	public function onPreRunPage($param)
	{
		$this->raiseEvent('onPreRunPage',$this,$param);
	}
`

**Comment by ctrlaltca** [comment]
This sounds like a nice addition to me

**Comment by ctrlaltca** [comment]
Fixed in #751
