### ISSUE TITLE
Lack of Timing and Memory Performance logging. TApplication records initial start time and memory usage.  #enhancement

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#736]
TApplication should be logging its start time and initial memory usage for performance metrics.

there could be a TPageLoadTime control to go with that to show the load time of the page.

**Comment by ctrlaltca** [comment]
TLogger already reports microtime and memory usage, and its output can be routed on different places.
What would be the benefit of having a web control? Could it be implemented as an async alternative to TBrowserLogRoute?

**Comment by belisoful** [comment]
I agree that TLogger does report microtome, but do we need a whole class just to capture the start time?  Shouldn't startTime be an application/system variable rather than found in a separate loaded module?

**Comment by belisoful** [comment]
this change was reverted in my code base.  I still have the change should it be wanted.
