### ISSUE TITLE
Should Theme Skin Templates not have their classes and attributes validated?

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#737]
Currently, Theme Skins are treated as standard templates and as such are validated for classes and attributes.  Such strictness is useful for templates that are rendered.  Is such strictness necessary for Skinning?

Maybe we should turn off class/attribute validation for theme Skin templates.  If a custom Control class is deleted (or theme reused from another site), Should the skin throw an error because it couldn't find the class?

I propose that Theme Skins have their class/attribute validation turned off so classes in the skin that don't exist don't throw an error.

I already have this change coded up, but I'll wait for discussion until posting.

**Comment by belisoful** [comment]
Application of a skin is where errors would take place rather than on skin validation.  This seems like preferred behavior.

The Template acts as a storage of skin parameters, rather than it being rendered.  As such, validation is less important.

**Comment by ctrlaltca** [comment]
If I get it correctly you mean that when you define a skin that applies to a few classes/controls, you currently receive a parsing errors on the skin template if one of the classes is not available in the application.
To make the same skin it reusable in multiple apps, you currently need to remove from the skin all the definitions for classes that are not available in that specific app.
Ignoring them would make the skin more reusable. If a skin contains errors, they will still be reported when the skin gets appllied on a control.
This looks like a good idea.

**Comment by belisoful** [comment]
I think you got it. yes.

**Comment by belisoful** [comment]
merged.
