### ISSUE TITLE
TApplicationConfiguration::loadParametersPhp $service is unset

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#739]
https://github.com/pradosoft/prado/blob/70505dbe2b4d9ff8058ec3fc02ace62364be7073/framework/TApplicationConfiguration.php#L347

$service variable is not set.  This probably is meant to be $parameter

This would affect any applications trying to load parameters via PHP where the parameter is an object

**Comment by ctrlaltca** [comment]
Fixed in #747
