### ISSUE TITLE
in Yii, behaviors can also be arrays with "class" and its properties as the other key=>values. PRADO should have it too

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#740]
attaching behaviors has 2 types supported: string of behavior class name, and behavior instance, 

a 3rd type should be supported and is found in Yii: 
`['class'=>'MyObjectBehavior' property1="value1" prop2="value2" attribute1="value3"...]`

This would need to be supported in ClassBehaviors too.

I have the changes to TComponent and it works in unittest but my computer crashed and wasn't able to write the new unit tests yet.

**Comment by ctrlaltca** [comment]
Fixed in #749
