### ISSUE TITLE
TSecurityManager::setHashAlgorithm uses hash_algos() rather than hash_hmac_algos() - some algos may be set that are not supported by hmac

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#742]
https://github.com/pradosoft/prado/blob/6ed3101a3f68efe307ceb02c8c90456dfd75fde1/framework/Security/TSecurityManager.php#L152

This update is on my branch via 
https://github.com/belisoful/prado/commit/0a6f9abcedd4c0fb78fd1c98aee2d622183eec06

**Comment by ctrlaltca** [comment]
Yep, that requires php 7.2.
We should either raise the minimum required php version or use `function_exists()` to fallback to the old method.

**Comment by belisoful** [comment]
Good point!  Thank you for the update on this.  I'll add the check to my branch.

**Comment by belisoful** [comment]
implemented on my branch as you suggested.
https://github.com/belisoful/prado/commit/a4c645c43985071c8affc56ce9afe1d54c81598f

**Comment by ctrlaltca** [comment]
Fixed in #747
