### ISSUE TITLE
Converting standard LTR into RTL... is there a standardized mechanism to determine RTL?

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#744]
Is there a method for determining the text direction LTR or RTL within globalization? 

Here are the languages that should be RTL:
from https://lingohub.com/academy/best-practices/rtl-language-list
`
['ar', 'arc', 'dv', 'fa', 'ha', 'he', 'khw', 'ks', 'ku', 'ps', 'ur', 'yi']`

This could be hard coded or the translator could be used to translate the text 'ltr' and check the output for 'rtl'.  This is how wordpress does RTL determination.

**Comment by ctrlaltca** [comment]
To determine id RTL or LTR:
```php
$o = new \Prado\I18N\core\CultureInfo('ar');
return $o->findInfo('layout/characters');
```

**Comment by belisoful** [comment]
Sir, you are an impressive person!

This seems like something that Globalization should encapsulate.  RTL is an important application variable for globalization.

This outputs the text (without quotes):
`'right-to-left'`

**Comment by ctrlaltca** [comment]
When I rewrote the globalization classes to use php's intl extension i implemented the bare minimum necessary to get all the existing classes working. There's a lot of room for improvements

**Comment by belisoful** [comment]
Ah.  Thank you for the re-write!  I cannot overstate how brilliant and hard working you are.

The RTL determination may be something I'll add to TGlobalization shortly.  If that is the case, I'll probably add *rtl.css support in themes. That way when globalization is RTL, the RTL extension css files are automatically added in the theme, otherwise *rtl.css will not be added.

Wordpress has RTL determination and automatically adds RTL css files when needed.  This is something PRADO should be doing as well.

**Comment by belisoful** [comment]
https://github.com/pradosoft/prado/pull/756/files

This pull request adds Globalization RTL determination and Ttheme RTL support.

**Comment by belisoful** [comment]
RTL support added
