### ISSUE TITLE
THttpSession throws "Cannot regenerate session id - headers already sent" warning when changing users in CLI with text printed on the screen

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#758]
When operating in CLI mode, Switching users after text has been printed causes session_regenerate_id to throw a warning:

[Warning] session_regenerate_id(): Cannot regenerate session id - headers already sent (@line 190 in file /Applications/Ampps/www/app/protected/vendor/pradosoft/prado/framework/Web/THttpSession.php).   
#0 [internal function]: Prado\Prado::phpErrorHandler(2, 'session_regener...', '/Applications/A...', 190, Array)
#1 ${PradoFramework}/Web/THttpSession.php(190): session_regenerate_id(true)
#2 ${PradoFramework}/Security/TAuthManager.php(398): Prado\Web\THttpSession->regenerate(true)
#3 ${PradoFramework}/Security/TAuthManager.php(414): Prado\Security\TAuthManager->updateSessionUser(Object(Prado\Security\TUser))
#4 ${PradoFramework}/Util/Cron/TCronModule.php(275): Prado\Security\TAuthManager->switchUser('admin')

**Comment by ctrlaltca** [comment]
Fixed in #759
