### ISSUE TITLE
Somehow I merged my branch into PRADO.  That was an accident. 

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#768]
I am so sorry about this.  I was merging changed back into my branch when, I guess I wasn't paying close enough attention, and merged my branch into Prado by accident!

This is an accident.

**Comment by belisoful** [comment]
I've been trying to be as careful as possible with the branches.

**Comment by belisoful** [comment]
https://github.com/pradosoft/prado/commit/9d4d6fe4d2dc2364ead30cc749759747f5c802c2 

was a merge the wrong way.  my humble humble apologies.

I apparently need a break from working so hard.  I'll be back shortly to correct the error as best I can.  if you know how to easily revert the change, please do so.  My humble apologies.

**Comment by ctrlaltca** [comment]
Don't worry, mistake happens to everybody.
I've reset master to the last merge of yesterday's PR.
This was a forced push, so commit history will break if you were following that branch.

**Comment by belisoful** [comment]
thank god you know more about this than I do.

**Comment by belisoful** [comment]
I reset my branch too.  I'm glad for the tutorials on how to do that. but now it's showing even with Prado master. no changes in the diff

**Comment by belisoful** [comment]
I reset my branches.  Yay for saving  copies.
