### ISSUE TITLE
Class 'JSMin\JSMin' not found when Application in Normal or Performance Mode

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#770]
PHPStan is not reporting any issues on GitHub. but phpstan is throwing three errors, including JSMin not found on my dev computer

------ ------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   Util/TFirePhpLogRoute.php                                                                                                                       
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------ 
         Prado\Exceptions\TPhpErrorException ([Unknown Error] Array and string offset access syntax with curly braces is deprecated (@line 1363 in file  
         /Applications/Ampps/www/app/protected/vendor/firephp/firephp-core/lib/FirePHPCore/FirePHP.class.php).) thrown while looking for class FirePHP.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                              
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------ 

 ------ -------------------------------------------------------------------- 
  Line   Web/Javascripts/TJavaScript.php                                     
 ------ -------------------------------------------------------------------- 
  296    Call to static method minify() on an unknown class JSMin\JSMin.     
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   Web/Services/TSoapServer.php                                                                                                                                  
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  18     Prado\Exceptions\TPhpErrorException ([Unknown Error] Array and string offset access syntax with curly braces is deprecated (@line 156 in file                 
         /Applications/Ampps/www/app/protected/vendor/pradosoft/prado-wsdlgenerator/src/WsdlGenerator.php).) thrown while looking for class Prado\Wsdl\WsdlGenerator.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                                                                            
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by belisoful** [comment]
my compose issue.

**Comment by belisoful** [comment]
incorrect, still an issue with a proper composer install/update

**Comment by ctrlaltca** [comment]
About firephp: the error is already resolved upstream, i sent a patch some time ago: https://github.com/firephp/firephp-core/pull/62

About jsmin: ùI'm unsure why the autoloader can't find jsmin, it seems to work here.

About wsdl-generator: already fixed, patch is here: https://github.com/pradosoft/prado-wsdlgenerator/commit/f95d6d914cc856d32e173ee06bca383b907c62c3

I guess that's something wrong with composer on your prado/app using prado installation.
I would try to delete the "vendor" folder (or protected/vendor inside an app) and run composer install again.

**Comment by belisoful** [comment]
Thank you. let me see what's going on, if I can.

**Comment by belisoful** [comment]
PHPStan is not giving an error any more.  I didn't do anything different.  But the app is still giving a JSMin problem.  My computer may be having issues.  :-/
