### ISSUE TITLE
Merged TMap and TPriority Map changes with Unit Tests, thought it was merging just the documentation

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#772]
I thought I was merging ONE change to the documentation but merge incorporated all the changes of TMap and TPriorityMap. that I had pushed up to the PR INCR.

Github was not clear in changing the documentation merge so I pushed the button.

If you want to roll back Prado please go ahead.  This change has unit tests and TMap_Behaviors.

again, my humble apologies for pulling the PR without your review.  I didn't know GitHub was going to merge the PR rather than just one part of one documentation on one file.  User error, but also poor/misunderstood GitHub documentation.

**Comment by belisoful** [comment]
This is a solid PR, btw.  It has been proofed and proofed and proofed again.  Still getting how GitHub works.

**Comment by belisoful** [comment]
The TMap and TPriority Map dynamic events are needed for TParameterizeBehavior and TDbParameterModule, in development.   TParameterizeBehavior still needs a test unit written but TDbParameterModule is ready for prime time.

If you want to see how these dynamic events are used, see TDbParameterModule:
https://github.com/belisoful/prado/blob/master/framework/Util/TDbParameterModule.php

**Comment by belisoful** [comment]
oh boy.  I don't like the changes being made without review.  I am just not confident in myself.

**Comment by ctrlaltca** [comment]
Don't worry, I took a quick look at the changes and they looks fine, let's keep them.

**Comment by belisoful** [comment]
Thank god.  I got very worried for a moment.  My anxiety is cranked up to 1000 due to personal circumstances.  It's not good.   I have a minor change to the TMapRouteBehavior which was causing the anxiety.  I'll check these changes in next.
