### ISSUE TITLE
I18N for base language kits (PHP Message Source) for built in texts, like 'megabyte', and console

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#782]
We should have a base language kits for various languages like Yii has.  They translate various built in system texts like kilobyte, megabyte, seconds, minutes, ok, cancel, etc

**Comment by ctrlaltca** [comment]
You can get that data from the intl bundles accessible via \Prado\I18N\core\CultureInfo.
Have a look at https://intl.rmcreative.ru/unit-data/en_US to see the available fields from intl.

**Comment by belisoful** [comment]
I had no idea!  thank you!

**Comment by belisoful** [comment]
I see why PRADO is using CultureInfo.  very interesting.  I need to revise TDataSize to use that.  I've been worrying about TTimeAgo having I18N as well, but this resolves that issue as well.   wow.   Thank you.  you are blessed.

**Comment by belisoful** [comment]
CultureInfo is not loading the unit information.  I added it as.a $bundleName.  It wouldn't load here.  I manually tried the code and no go.  maybe it's my version of php?

**Comment by ctrlaltca** [comment]
Yep it looks like i didn't implement all the bundle names.
You just need to add `'units' => 'ICUDATA-unit',` here: https://github.com/pradosoft/prado/blob/master/framework/I18N/core/CultureInfo.php#L75 , then you'll be able to query them, eg:
```php
$o = new \Prado\I18N\core\CultureInfo('it');
return $o->findInfo('units/digital');
```

**Comment by belisoful** [comment]
MacOS 10.15.7, PHP 7.3.11, all the others work but ICUDATA-unit.  very strange.

**Comment by belisoful** [comment]
I'd like to have TDataSize use this.  The TTimeAgo can also use it.

**Comment by belisoful** [comment]
what are you thoughts on having translation files for shell?

**Comment by ctrlaltca** [comment]
Probably a low priority task, but still welcome
