### ISSUE TITLE
TUserManager only links to xml UserFiles and ignores PHP style configurations

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#791]
TUserManager::UserFile only checks for '.xml' files and fails to find the php configuration file.

When loading the Configuration file under php, but the xml file is found, TUserManager fails to load.

https://github.com/pradosoft/prado/blob/dc84c013f7a7cd7d90ae3633746056be8982bd9e/framework/Security/TUserManager.php#L242

This line is hardcoded to '.xml' rather than checking for php configurations when php configuration is enabled.

This error causes 
https://github.com/pradosoft/prado/blob/dc84c013f7a7cd7d90ae3633746056be8982bd9e/framework/Security/TUserManager.php#L115

to fail.

**Comment by ctrlaltca** [comment]
I confirm, that part of the code is plain wrong.

**Comment by belisoful** [comment]
fixed
