### ISSUE TITLE
[PHP8.1

### ISSUE THREAD

**Issue by zendre4** [pradosoft/prado#807]
Hello,

In PHP 8.1 I found this error when I try to submit a form (with callback/ajax) : 

![2022-03-24_13-37](https://user-images.githubusercontent.com/9673982/159918852-8555deec-7b12-4c91-8d29-03571e7c1e06.png)

I don't know where it comes from for the moment

**Comment by ctrlaltca** [comment]
Can you please check if https://github.com/pradosoft/prado/commit/b3c7556691ca71c6e95f7b9707284f0233406db9 works for you?

**Comment by zendre4** [comment]
Yes this fix is working. Thank you ! I have other bug, but I will open a new issue.
