### ISSUE TITLE
MethodsClassReflectionExtension on TComponent required for PHPStan to validate "dy" events

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#818]
In updating cron, a tweak to a dynamic event was needed.  Dynamic 'dy' events are an uncommon use of magic methods that is open rather than predefined.  PHPStan requires everything to be predefined.  Forcing PHPStan to work by including all "dy" methods is not a long term solution because PRADO composer extensions will not be able to PHPStan validate themselves against dynamic events.  

In looking into PHPStan, they do not consider @method to be anything but predefined.  However, they have included a solution with MethodsClassReflectionExtension for strange magic methods like dynamic events.

see the second half of this page:  https://phpstan.org/developing-extensions/class-reflection-extensions

Does PRADO have a phpstan configuration file?  How does GitHub do an automatic phpstan?  does GitHub have a configuration?

Basically, it looks like a custom class implementing interface PHPStan\Reflection\MethodsClassReflectionExtension for TComponent is needed.  All PRADO classes would then inherit the phpstan magic method validation for "dy" and "fx" events.

The build up of "dy" events in TCallChain and in other classes should be removed.

A folder for phpstan in PRADO is needed to contain the MethodsClassReflectionExtension and MethodReflection implementation.  The phpstan configuration would be to be created/updated as well.

```
namespace Prado\PHPStan;
use PHPStan\Reflection\MethodsClassReflectionExtension;
class DynamicMethodsClassReflectionExtension implements MethodsClassReflectionExtension {
     public function hasMethod(ClassReflection $classReflection, string $methodName): bool
     {
          return strncasecmp($methodName, 'dy', 2) === 0 || strncasecmp($methodName, 'fx', 2) === 0;
     }
}
```

I don't know enough about PHPStan to comment on implementing MethodsClassReflectionExtension::getMethod

The documentation says to include this in the phpstan configuration to register the MethtodsClassReflectionExtension implementation.
```
services:
	-
		class: Prado\PHPStan\DynamicMethodsClassReflectionExtension
		tags:
			- phpstan.broker.methodsClassReflectionExtension
```

In this example, the Prado folder for phpstan is "PHPStan" and the dynamic event class reflection extension in called "DynamicMethodsClassReflectionExtension"

**Comment by ctrlaltca** [comment]
> Does PRADO have a phpstan configuration file

Yes, even if it's barebone:
https://github.com/pradosoft/prado/blob/master/phpstan.neon.dist

> How does GitHub do an automatic phpstan?

From  this github action definition:
https://github.com/pradosoft/prado/blob/master/.github/workflows/prado.yml#L61

 
I can try to have a look at this if you want

**Comment by belisoful** [comment]
Please have a look at it.  It should be relatively easy to resolve.  It is a "fix" that i plan to get to eventually, but if you can more quickly, perfect.

I have my hands full right now with Cron, composer extensions, and a new TEmailTemplate for making emails from a PRADO template.

It's funny how one can look right at the phpstan.neon.dist in the main directory and _not_ see it...  😅

**Comment by ctrlaltca** [comment]
Done in https://github.com/pradosoft/prado/commit/533bc07846c9ee69ab3551367c37f4ea4e1ca1cd
You may try starting to remove he dummy @methods doc comments, it should work now

**Comment by belisoful** [comment]
when a module calls it, they should remain for documentation,  but the stubs needed prior for php-cs-fixer conformance should be removed (eg TCallChain).  I'll get to that as i have the time, unless you want to.

**Comment by belisoful** [comment]
This can be closed on merge.

**Comment by belisoful** [comment]
Holiday Bug patching cheers!  Build up of phpdoc in TCallChain is removed.
