### ISSUE TITLE
TComponent::__isset stops checking at the first behavior instead of finding the behavior with the property/event

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#821]
https://github.com/pradosoft/prado/blob/46bc20d67bfa655de2bbb05128d883c53161c3cf/framework/TComponent.php#L795

Should read:

`if ((!($behavior instanceof IBehavior) || $behavior->getEnabled()) && ($behavior->canGetProperty($name) || $behavior->hasEvent($name))) {`

**Comment by ctrlaltca** [comment]
This looks like a fix if an object has more than one behavior attached, totally needed.

**Comment by belisoful** [comment]
Ready to close on merge

**Comment by belisoful** [comment]
Holiday Bug patching cheers! This is an obvious bug, handled by other functions in TComponent.  This should have been obvious to me during initial development.
