### ISSUE TITLE
TComponent::*tachClassBehavior should return TClassBehavior or event results for regular TBehaviors.

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#822]
Just like attaching behaviors, the behavior should be returned.  This allows for init based on application configuration.

https://github.com/pradosoft/prado/blob/46bc20d67bfa655de2bbb05128d883c53161c3cf/framework/TComponent.php#L1474
should be
```
$behaviorObject->raiseEvent('fxAttachClassBehavior', null, $param);
return $behaviorObject;
```

https://github.com/pradosoft/prado/blob/46bc20d67bfa655de2bbb05128d883c53161c3cf/framework/TComponent.php#L1504
should be
`return null;`

and 
https://github.com/pradosoft/prado/blob/46bc20d67bfa655de2bbb05128d883c53161c3cf/framework/TComponent.php#L1510
should be 
```
$behaviorObject->raiseEvent('fxDetachClassBehavior', null, $param);
return $behaviorObject;
```

**Comment by ctrlaltca** [comment]
Is there any case where you may need both the behaviorObject and the event responses ? Maybe return them both?

**Comment by belisoful** [comment]
This initial decision to return the event responses was because i wasn't forward thinking.  That's the data available, so return it.

But my thinking now is that attaching and detaching should return the behavior.  the behavior, as a return result, is further used by the TBehaviorModule to call its init($config) for any more complex behavior configurations.  If the [class] behavior is not returned, TBehaviorModule doesn't have a behavior to initialize.  This is the behavior update/tweak.

**Comment by belisoful** [comment]
Also note, the return result of the *tach class event was not documented on purpose for this very reason. FYI.

**Comment by belisoful** [comment]
I'm looking at this and remembering....  This is a complex issue that requires some noodling on.

The *tachClassBehavior can attach a TClassBehavior, which would be appropriate to return the behavior object.  However, regular TBehavior(s) can be virtually attached and then instanced on target class when the target class is instanced.  Meaning, there is no behavior object to return.

That's the complex aspect and why I originally decided to just return the event results rather than the object.

This is my current thinking for the attach and detach Class Behavior core is

```
	$behaviorObject = self::instanceBehavior($behavior);
	$isClassBehavior = $behaviorObject instanceof \Prado\Util\TCLassBehavior;
	$param = new TClassBehaviorEventParameter($class, $name, $isClassBehavior ? $behaviorObject : $behavior, $priority);
	self::$_um[$class] = [$name => $param] + self::$_um[$class];
	$results = $behaviorObject->raiseEvent('fxAttachClassBehavior', null, $param);
	return $isClassBehavior ? $behaviorObject : $results;
```
and

```
	$param = self::$_um[$class][$name];
	$behavior = $param->getBehavior();
	$behaviorObject = self::instanceBehavior($behavior);
	$isClassBehavior = $behaviorObject instanceof \Prado\Util\TCLassBehavior;
	unset(self::$_um[$class][$name]);
	$result = $behaviorObject->raiseEvent('fxDetachClassBehavior', null, $param);
	return $isClassBehavior ? $behaviorObject : $results;
```

The TClassBehavior was not being shared and was being instanced per target class instance when a TClassBehavior object was not specified as the $behavior... so this fixes the TClassBehavior Bug when a class string or array is sent as a $behavior

**Comment by belisoful** [comment]
The way this is resolved is that the Class Behavior is returned if it's an IClassBehavior and it returns the array of attached behaviors if it's a per instance IBehavior.   Unit tests written and phpdoc updated.   commit pending...

**Comment by belisoful** [comment]
This can be closed with merge.

**Comment by belisoful** [comment]
Holiday bug fixing cheer!!!   This resolves a long standing question I had regarding this code: what is the return value.  I'm glad this is resolved now
