### ISSUE TITLE
TComponent needs a getBehaviors to return all behaviors of the class

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#826]
something simple like this is needed:

```
	/**
	 * Returns all the behaviors attached to the TComponent.  TBehavior[s] may
	 * be attached but disabled.
	 *
	 * @return array all the behaviors attached to the TComponent
	 * @since 4.2.2
	 */
	public function getBehaviors()
	{
		return $this->_m ?? [];
	}
```

**Comment by ctrlaltca** [comment]
That's fine, but i can see some problems if the returned result is modifiable by the caller.

**Comment by belisoful** [comment]
Would this quell the concern?
`return $this->_m ? $this->_m->toArray() : [];`

**Comment by ctrlaltca** [comment]
The array should be passed by copy (not reference), so yes

**Comment by belisoful** [comment]
Holiday Bug patching cheers! This has been a long time coming.
