### ISSUE TITLE
TTemplateManager needs  instancing subclasses of TTemplate and input culture for non-user based localization

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#827]
I'm working on adding a TEmailTemplate for capturing and dealing with published files as: links, automatic email attachments, or embedded data.  It acts as a publish rerouter.  Default behavior is like a webpage, the asset is publish in a the assets folder and linked in the email.

However, TTemplateManage need to be able to accept a subclass of TTemplate, and culture for localizations not based upon the request/session.  A.TEmailTemplate could be sent to a user where the active web user is not the email receiver and needs localization for that specific user.

eg. mail list module where users languages are captured when they subscribe and used to customize future emails to them.

Such templates would get the caching speed bump too.

**Comment by ctrlaltca** [comment]
A property could be added to TTemplateManager that can be set to the class to be used for generated templates, eg. what is currently used by TUrlMapping for DefaultMappingClass:
```php
class TTemplateManager ...
...
	protected $_defaultTemplateClass = '\Prado\Web\UI\TTemplate';

	public function getDefaultTemplateClass()
	{
		return $this->_defaultTemplateClass;
	}

	public function setDefaultTemplateClass($value)
	{
		$this->_defaultTemplateClass = $value;
	}
```

TTemplateManager::getTemplateByFileName() would them make used of this class name to instantiate new templates.

Localization is a bit harder and would probably require a few more methods.

**Comment by belisoful** [comment]
The surprisingly simple solution i have working right now is to redefine this:
https://github.com/pradosoft/prado/blob/fcc6b66a5aea385f163335e18f2e28d22cdd3c6c/framework/Web/UI/TTemplateManager.php#L75

to this
`public function getTemplateByFileName($fileName, $tplClass = "\\Prado\\Web\\UI\\TTemplate", $culture = null)`

First to check that the $tplClass is an instance of TTemplate for sanity. Then instance the class from that.  $culture is passed through to the localize function. null just uses the application globalization.

It's not really a change of the defaultTemplateClass,  It's an overriding.  The TEmailerModule doesn't need to change the default, it should work in parallel to the default.  Working on the TEmail functionality is providing a lot of unique insight into how PRADO can work better.

**Comment by ctrlaltca** [comment]
Simple solutions are always the best.
Still, adding a DefaultTemplateClass property would make this configurable in application.xml

**Comment by belisoful** [comment]
I see what you are suggesting with the DefaultTemplateClass.  So i agree.  That does make sense.

**Comment by belisoful** [comment]
I think you are right about not needing to check the interface as a class.  I'll do a bump on this shortly.

**Comment by belisoful** [comment]
I am so glad this one is wrapped up.
