### ISSUE TITLE
TApplication::setUser should have an "onSetUser" event

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#828]
Setting a user in the system is a significant event, and should probably have its own event.

I'm thinking that under CLI, setting a user happens under cron for each specific job.  Setting the task users HTTP Language settings would need to happen here in a proper TUserModule.  the user's language would need to be retained from their web interaction, but is something that would be necessary to send localized emails to/by users via cron offline.

**Comment by ctrlaltca** [comment]
TAuthManager has onLogin/onLoginFailed/onLogout, but already misses the case when switchUser() is called.
Do you have a TAuthManager in your use case? That's probably a better place to emit user-related events than TApplication

**Comment by belisoful** [comment]
The use case is for cron with a TUserManager and without TAuthManager.  Cron directly sets the user of the application based upon the task's user without regard for the TAuthManager.  Thoughts?  Many options.  including changing cron.

https://github.com/pradosoft/prado/blob/fcc6b66a5aea385f163335e18f2e28d22cdd3c6c/framework/Util/Cron/TCronModule.php#L470

**Comment by ctrlaltca** [comment]
So, it makes sense to keep the existing events specific to authentication inside TAuthManager , and adding a new event to TApplication as you suggested initially.

**Comment by belisoful** [comment]
Agreed.

**Comment by belisoful** [comment]
This can be closed on merge.

**Comment by belisoful** [comment]
Holiday Bug patching cheers!  This makes a lot of sense.
