### ISSUE TITLE
TCallChain incorrectly reverses order...

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#846]
https://github.com/pradosoft/prado/blob/16970424928d9f794939d7f26155fbff448a7b27/framework/Util/TCallChain.php#L102

This shouldn't be reversed.  The expected function is the call chain in priority sorted order.

**Comment by belisoful** [comment]
this can be closed on merge.

**Comment by ctrlaltca** [comment]
Fixed by #850
