### ISSUE TITLE
TUtf8Converter needs language settings for iconv and TEscCharsetConverter for converting ESC charset and iconv charset

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#864]
Namaste!

This is a request for information regarding personal experience, info, webpages, algorithms, and/or code with implementing/parsing Escape Character Code Sets for conversion into iConv::charEncoding.

In IPTC, strings in the second record set and above are stored in a character encoding specified (possibly) in the IPTC.  These character encodings are stored in escape data.  That escape data needs to be read and parse.   The IPTC char set is then used to convert all proper string data to UTF-8 internally.

I have a halfway decent first iteration of the IPTC CharSet Escape Char Code into iConv::charEncoding.

Esc control characters (controlling the char set) is found here:
https://en.wikipedia.org/wiki/ISO/IEC_2022

and ANSI and the national variants with the ESC values are here:
https://en.wikipedia.org/wiki/ISO/IEC_646

The thing I'm looking for experience and commentary on the ESC char set conversion.  Is there a PHP method I am missing to make this easier?   Is there an easy way to process ESC character control characters?

How would you parse ESC char set data in IPTC?

Here is the official IPTC spec:
http://www.iptc.org/std/IIM/4.1/specification/IIMV4.1.pdf

And the Character Encoding is found in '1#90'. record 1, tag id 90.  Common Character encodings are in appendix C.

How is G0, G1, G2, and G3 handled differently?  How is C0 and C1 handled?  In reading the ESC char set, do the other ESC values need to be restored if the charset changes?

My current thinking is to have a configurable default IPTC Charset when an IPTC has no charset.  Then have an Output IPTC charset configuration (None, Preserve, etc ['UTF-8', 'CP1252',...]).  The default input is ASCII and the default output is UTF-8.   This is the default behavior of other platforms as well.

**Comment by belisoful** [comment]
The way iconv accounts for national variations of ASCII is with "setlocale".   At least that is what I have gathered so far.

Can someone confirm?

**Comment by ctrlaltca** [comment]
In the documentation of the function iptcparse: https://www.php.net/manual/en/function.iptcparse.php i've foud this snippet of code that may be relevant:
```php
$IPTC_Caption = "";
$size = getimagesize( $image_path, $info );
if (isset($info["APP13"])) {
    if($iptc = iptcparse( $info["APP13"] ) ) {
        $IPTC_Caption = str_replace( "\000", "", $iptc["2#120"][0] );
        if(isset($iptc["1#090"]) && $iptc["1#090"][0] == "\x1B%G")
            $IPTC_Caption = utf8_decode($IPTC_Caption);
    }
}
```

Iconv should be able to handle all the variants of aschii by naming them eg, "Windows-1252", "ISO-8859-15", "ISO-8859-1", "ISO-8859-6", "CP1256", ...

**Comment by belisoful** [comment]
"\x1B%G" is the ESC character code for UTF-8 encoding.   That was the first encoding I put in placed.  There is a lot of conversion taking place.

I'm thinking of putting the encodeEscCharset and decodeEscCharset into the TUtf8Converter.  That uses iconv and hence can be subtly influenced by setLocale for the ASCII encoding.    That seems to be an appropriate place for those methods.

When "\x1B%G" is found, the code is converted into "UTF-8".  I have coded about 2 dozen other character codes and locales.  I haven't found the Chinese or Hindi charsets yet.

**Comment by belisoful** [comment]
BTW, I can't wait to get this new asset manager in place, with the dot, and some utility classes.   I'm still chugging along.  You can see the complexities and engineering issues I'm running into in the last leg here.

**Comment by ctrlaltca** [comment]
It's quite a hard task indeed. If you want you can leverage the usage of external libraries, eg. https://github.com/diderich/metadata

**Comment by belisoful** [comment]
A brief overview of the link: those are great examples.  It's read only though.  So many libraries have such a partial fit.

I've been studying JFIF, JFXX, IPTC, EXIF, WebP, PNG, TIFF, IFD, JPEG, ESC charsets/encoding, and a little of XMP metadata to gather how to unify the systems for Prado for reading, matching, updating, and writing. 

I haven't found an open source implementation of JFIF or JFXX.  These are the most simple to implement and are done with unit tests.  :). They provide embedded JPEG thumb nailing.  Easy peasy.  Most JPEGS are JFIF but don't use the thumbnail feature.

In the link, The IPTC and EXIF are only partial implementations of the standard.  Having studied the IPTC it would be great to have an "as full as possible" implementation for PRADO so people can actually utilize it as fully as possible.  Facebook embeds IPTC unique data for tracking how users download and share images.   yeah. it can be useful.

Anywho, the implementation I have so far of IPTC is awesome.  It's an TPriorityMap to keep records ordered (1, 2, 3, 7, etc).  Records can be accessed by record tag or by tag name, case insensitive.  The class can parse an IPTC data and write IPTC data.  The charset is the last bit before writing the unit tests.  The TIPTC class is very _Prado_ and very developer and user friendly.  I consider this new code to be a gold standard setting class implementation, but eh, let's (as in me) get the unit tests done first before tooting any horns.  It's a very thorough implementation ripe for continued use and development.

The example you shared also deals with Photoshop IRB metadata,  I have a class for that.

A full implementation of IFD would be as useful as SOAP and JSON services.  It is a useful way to read and store data in a file/database regardless of format or application, should people want it.  Yes, php can serialize an object or array into a PHP string or JSON, but IFD is a widely supported *binary* file format.

I think PRADO, in 2023, should have a wicked awesome IFD implementation.  That is part of asset publishing and file processing (IO).

The IFD can be subclassed with specifics for TIFF.  That is the place for imageCreateFromTiff and imageTiff (read and write tiff).  That is out of the spec for this release for now, but is actually easy to implement.  Others have.

EXIF then needs to subclass TIFF.  

I don't expect EXIF to be as complex with the char sets, at least not yet, but it is an order of magnitude larger than IPTC.

The internal structure of EXIF needs to be handled in such a way as to read and write.

I am haven't look too deeply into charset processing in EXIF.  The EXIF standard is here:
https://web.archive.org/web/20190624045241if_/http://www.cipa.jp:80/std/documents/e/DC-008-Translation-2019-E.pdf
If you want to take a dive into it.

One of the main reasons for all this headache is that Images that get processed should retain their metadata...
   ...but also be able to scrub EXIF GPS data on images for security.

**Comment by belisoful** [comment]
What is the best way to parse ESC char codes?   existing implementation?

**Comment by belisoful** [comment]
https://www.sljfaq.org/afaq/encodings.html

This is a resource for escape sequences regarding Japanese character encodings.

Best practices.  That's what I'm looking for in mapping ESC sequences to character encodings.

**Comment by belisoful** [comment]
For the lack of comprehensive discussion on the internet, I am going to break apart the 32 characters in the IPTC CodedCharacterSet by trimming and exploding the escape character.  Loop through all results, adding the escape character to the start - Check against a list of known ESC sequences for character encodings.

All other ESC data (like control character codings?) are wiped away.  the first char encoding is accepted.

When writing the variable, the reverse is performed matching the character encoding set to the ESC char encoding sequence. 

I don't know what best practices there are around this.  The list of languages is oddly large because many of the char sets are replicated 4 times [with 4 different byte sequences (G0, G1, G2, G3.  ??) in the 2/3 byte].   writing the encoding to ESC sequence always picks G0 (lowest byte of the 4 possible).

I'm not sure if there is any other logic needed.  This is in the Prado/Util/TUtf8Converter class because it generates the charset for conversion to and from UTF.   If my study of this is correct, there are some bizarre flaws/quirks in PHP and iconv that should to be documented/corrected.

I'm going to put the issues down here with PHP in case this is useful for anyone else.

First, ASCII national variations seem dependent upon php "setLocale", That depends on the user http settings, and that makes sense, we can take the users text as it is.  Setting the locale for char encoding conversion makes sense but it needs to be able to be programatic from iconv rather than requiring a setLocale and unset.  The presumption encoded into PHP [iconv] is that the output will be to the user rather than independent of the user.

Second, setLocale applies to the thread with multiple concurrent connections.  So one user can setLocale and it will affect other users.  Thus keeping the setLocale proximal to iconv is important to minimize clobbering if there is much string conversion taking place between users.  Parameterizing the locale within an iconv option would be useful to stop inter-user clobbering potential.

Third, there are encodings that should be included in standard iconv but aren't.  Specifically "ISO-5427" and "CSN 369103",  there may be more but I couldn't find a comprehensive list of esc coded character sets.

The two missing encodings can be found here:
ISO-5427.    https://en.wikipedia.org/wiki/ISO_5427.   (8 bit Cyrillic, 1979/1981)
ČSN (Czech technical standard) 369103.    https://en.wikipedia.org/wiki/KOI_character_encodings (also Cyrillic)

This RFI will change over to a code issue to added code to TUtf8Converter for handling escape coded char sets.

If anyone has a best practices reference for escape coded char sets or a comprehensive list of escape coded character sets, that would be awesome.  It's not a critical request though.

With this, TIPTC (not the new XMP kind but the original "old" style) is nearly complete.  It's a very cool and thorough implementation.  Most implementations just parse into an array with TagIds.  This parses into a TPriorityList to maintain order of the record sets.  It also handles Tag name to Tag ID conversion.  So values can be looked up by TagID or TagName which cannot be provided by a regular array.  It has the embedded [to] binary() function.  There are a few little touches to it that make it very clean and easy to use.
