### ISSUE TITLE
HTMLPurifier_Config and cache path

### ISSUE THREAD

**Issue by majuca** [pradosoft/prado#866]
Hi,

Prado is using HTMLPurifier for sanitization TTextBox and TSafeHtml. HTMLPurifier use a internal cache where the default path, if you don't configure one, is in its own library directory. Meaning in the vendor folder. Of course, vendor should not be writable for security reason. I propose to set the default cache to the runtime path like this for the TTextBox:

```
public function getConfig()
{
	$config = $this->getViewState('Config', null);
        if ($config === null) {
            $config = \HTMLPurifier_Config::createDefault();
            $config->set('Cache.SerializerPath', Prado::getApplication()->getRuntimePath());
        }
	return $config;
}
```
The same thing could be done for TSafeHtml.

If you are agree, I can propose a PR.

**Comment by belisoful** [comment]
I haven't studied HTMLPurifier.  It seems like a very good catch.   I can't say much about the proposed solution except the it does seem approximately correct.

Is there a reason why it does not have its own directory in Runtime?  Is there any reason to isolate the HTMLPurifier Serializer Cache Path for collisions?

**Comment by majuca** [comment]
You are right, the cache should be isolated. One other simple reason is just to know who create what. 

I see that for the TTextBox, a directory called HTML is created and for the TSafeHtml a directory called URI is created in the cache.

I will propose a PR where the cache is isolated in the runtime.
