### ISSUE TITLE
Permissisons in prado files project

### ISSUE THREAD

**Issue by majuca** [pradosoft/prado#869]
When installing Prado by composer, I see that a lot of files (.php, .tpl, .page, .xml, .sql, ...) has the exec permision. Is there any reason for that or is it a mistake on a previous commit?

Exemple:
...
./pradosoft/prado/tests/unit/Util/Behaviors/TBehaviorParameterLoaderTest.php
./pradosoft/prado/tests/unit/Util/Behaviors/TTimeZoneParameterBehaviorTest.php
./pradosoft/prado/tests/unit/Util/TLoggerTest.php
./pradosoft/prado/tests/unit/Shell/TShellWriterTest.php
./pradosoft/prado/tests/initdb_mysql.sql
./pradosoft/prado/tests/initdb_pgsql.sql
./pradosoft/prado/tests/test_tools/PradoGenericSelenium2Test.php
./pradosoft/prado/tests/test_tools/phpunit_bootstrap.php
./pradosoft/prado/tests/test_tools/README.txt
./pradosoft/prado/framework/Web/Javascripts/source/prado/activefileupload/ActiveFileUploadError.png
./pradosoft/prado/framework/Web/Javascripts/source/prado/activefileupload/ActiveFileUploadComplete.png
./pradosoft/prado/framework/Web/Javascripts/source/prado/activefileupload/activefileupload.js
./pradosoft/prado/framework/Web/Javascripts/source/prado/activefileupload/ActiveFileUploadIndicator.gif
...

Normaly, only ./pradosoft/prado/bin/prado-cli should have it, right?

**Comment by belisoful** [comment]
many of my files were duplicated and edited... That's how the error got into my commits if anything.

**Comment by ctrlaltca** [comment]
Yep, nothing should be executable except prado-cli
