### ISSUE TITLE
Use of Php traits

### ISSUE THREAD

**Issue by fabioman** [pradosoft/prado#875]
I'm using Prado 4.2.1 and I can't use Php Traits.
Is that normal? How can we use traits with Prado?

**Comment by ctrlaltca** [comment]
Do you mind sharing an example of what you are trying to do?
Traits are a php feature, i can't see a way prado can interfere with them.

**Comment by fabioman** [comment]
I have a complex form (with a lot of fields depending on the previous inserted field values and some repeaters) that I need to reuse in different place and I don't want to simply copy/paste

**Comment by ctrlaltca** [comment]
As far as i know traits are used to collect methods that are used in different classes, as a way to workaround php missing multiple inheritance. If you have a single form/page, you can't include a trait more than once in a single class.

**Comment by fabioman** [comment]
Yes and those method from the trait could be used to set the form behavior. Don't they?

**Comment by ctrlaltca** [comment]
Made a simple test starting from the [helloworld demo](https://github.com/pradosoft/prado-demos/blob/master/helloworld/protected/pages/Home.php):

```php
<?php

trait MyTrait
{
    public function sayHello() {
        return 'hello from trait';
    }
}

class Home extends TPage
{
	use MyTrait;

	public function buttonClicked($sender,$param)
	{
		$sender->Text = $this->sayHello();
	}
}
```

And the result is:

![immagine](https://user-images.githubusercontent.com/1631111/225093722-d7e08661-604c-44a6-b88b-8dfabb46d5c7.png)

**Comment by fabioman** [comment]
In the same file, it's normal that it works.
But I have a trait on different file and folder.
I have added the namespace path on my application.xml config `file`
`<using namespace="Application.traits.*"/>`

But when I try to include it on another a class file like this
`Prado::using("Application.traits.MyTrait");`

I have the following error coming from Prado::using() function `Prado::using("Application\traits\MyTrait");`


![screenShot](https://user-images.githubusercontent.com/6782828/225249230-e6e30128-d11d-4bbd-816c-926f43f49887.png)

**Comment by ctrlaltca** [comment]
Can you please test if https://github.com/pradosoft/prado/pull/876 fixes the error for you?

**Comment by fabioman** [comment]
I approve that it's working
