### ISSUE TITLE
Add stricter types on TList and TMap, minor corrections

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#889]
I'd like to add stricter types on the TList and TMap in the places that make sense and aren't open for overriding.

This affects TPriorityXXX, WeakCallableCollection, and a few other classes that subclass the base methods.

In TList and TMap, while the container array _d (holding the list items) are private, it makes more sense that they be protected instead so subclasses can have direct access to the data.  The TWeakList is going to need to scrub the container without parent accessors.  It also allows the TPriorityXXX to re-use _d rather than use its own _d with the parent _d becoming unused.   TPriorityXXX completely overrides the original use of _d but could use its parent variable non-the-less.

I've found a few redundant methods in TPriorityList.

and I have a trait for using a WeakMap as a caching mechanism in both TWeakCallableCollection and TWeakList.
TWeakMap and fixing TWeakCallableCollection

**Comment by ctrlaltca** [comment]
Everything looks good now
