### ISSUE TITLE
isSystemWindows function to check for windows

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#938]
There should be a common function for checking for windows. 

@ctrlaltca can you suggest what the best path might be?
 - Should it be in Prado Base class?
 - or maybe a Prado\Util\TEnvironmentHelper?
 - or maybe put it in TBitHelper?  (meh. it complements isSystemBigEndian.  )

Use Case: There are some properties of proc_open (aka priority and changing process priority) that is system dependent on shell commands.

Proc_Open is going to be using endian from TDataStream to enable binary data writing to pipes, so TBitHelper kind of does makes some sense from that perspective.

**Comment by ctrlaltca** [comment]
If it's only going to be used by a method to determine proc_open()'s options, i'd keep it near to the caller method (inside the same class)

**Comment by belisoful** [comment]
it's two methods for getting and setting the priority of a proc_open from the parent.  It's easy enough to set from the child , there is `proc_nice` for that.  But to set from the parent it requires a touch of shell_exec wizardry that is system dependent.  linux is simple enough, `ps` to get nice priority and `renice` to set it. but windows isn't so simple.

Given that it is kind of a systemic thing for people, I thought it would be nice to provide a function for that.  Kind of like determining the system endian is a systemic issue that is easily resolved so it's not reinventing the wheel each time.
