### ISSUE TITLE
TApplication::VendorPath and "Vendor" alias for composer directory

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#946]
Yii has a "VendorPath" property and "Vendor" Alias in their Application object.  We should probably have that.

**Comment by belisoful** [comment]
Can someone else handle this?  It should be simple. but it does require some custom testing.

As a model, use the Yii2::application object that has the property and generates the Alias:
https://github.com/yiisoft/yii2/blob/master/framework/base/Application.php

**Comment by ctrlaltca** [comment]
We already have that, see PRADO_VENDORDIR and https://github.com/pradosoft/prado/blob/master/framework/Prado.php#L76

**Comment by belisoful** [comment]
my apologies. you are correct.
