### ISSUE TITLE
php-doc "<code>" converted to "```php"

### ISSUE THREAD

**Issue by belisoful** [pradosoft/prado#964]
or "```html" if the example is html.   also `</code>` needs the ending triple "`"

This is the kind of maintenance thing @ctrlaltca usually handles silently in the night.  ;)

**Comment by ctrlaltca** [comment]
I'll take care of it silently in the night. :sleeping:

**Comment by ctrlaltca** [comment]
Wow, it looks that all the {@links } in the documentation are broken! blame on me for not checking it

**Comment by ctrlaltca** [comment]
Work in progress, see #965
