### ISSUE TITLE
Website shows Certificate error

### ISSUE THREAD

**Issue by sicutdeux** [pradosoft/prado#991]
Hi, just tried to use the website with https and i can see there is an issue with it... maybe related to the hosting, attaching a screenshot.

![Screenshot 2023-11-18 at 9 25 31 AM](https://github.com/pradosoft/prado/assets/8029652/4135603f-0bc4-4b01-be4e-7e9a0411bf49)

**Comment by ctrlaltca** [comment]
Fixed, thank you.
